<?php

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Konfiguriere den Twitch-Benutzernamen im Admin-Bereich.',
	'975011b2' => 'Twitch-Streamer',
	'3c103f4d' => 'Zeigt den Live-Status eines Twitch-Streamers (Spiel, Zuschauer, Titel, Vorschaubild) mit eingebettetem Player in einem Popup.',
	'1f88c31b' => 'Optionen',
	'79a32b9f' => 'Hilfe',
	'67b2d247' => 'Twitch-Benutzername',
	'71244a57' => 'Login (URL twitch.tv/<b>DEIN-LOGIN</b>), nicht der Anzeigename.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Siehe Hilfe-Tab, um diese Anmeldedaten zu generieren.',
	'41d3cbb9' => 'Stream öffnen',
	'f1c50f2d' => 'Eingebettetes Popup (Twitch-Player auf der Website)',
	'1b6c8b33' => 'Neuer Tab (twitch.tv)',
	'cc298ae3' => 'Offline anzeigen',
	'4990c8d6' => 'Immer anzeigen (mit OFFLINE-Badge)',
	'fdccaf5d' => 'Ausblenden wenn offline',
	'189cc521' => 'Client ID und Secret generieren',
	'a16d654a' => 'Melde dich auf <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> mit deinem Twitch-Konto an.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Name: <code>NeoFrag widget</code> (frei)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (für dieses Widget nicht verwendet, aber Pflichtfeld)',
	'5faa6ed1' => 'Kategorie: <code>Website Integration</code>',
	'3a798552' => 'Client-Typ: <strong>Confidential</strong>',
	'9451ddf0' => 'Erstellen → du erhältst eine <strong>Client ID</strong>',
	'cf2863ce' => 'Klicke auf die App → <strong>New Secret</strong> → kopiere das <strong>Client Secret</strong>',
	'd74ba844' => 'Füge beide in die obigen Felder ein.',
	'8c480bbb' => 'Das Widget verwendet <code>client_credentials</code>-Authentifizierung (Server-to-Server) — deine Besucher müssen sich nicht bei Twitch anmelden. Das Access-Token wird 60 Tage zwischengespeichert.',
	'4edf59a6' => 'Keine Anmeldedaten?',
	'38043231' => 'Das Widget funktioniert trotzdem: Es zeigt nur einen \'Auf Twitch ansehen\'-Button ohne Live-Status oder Stream-Details.',
	'98b98678' => 'Status nicht verfügbar (ohne API)',
	'e08bc8ce' => 'LIVE',
	'48b614a4' => 'Offline',
	'77baa327' => 'Live ansehen',
	'94d43c73' => 'Kanal ansehen',
];
