<?php
declare(strict_types=1);

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Konfiguriere den Twitch-Benutzernamen im Admin-Bereich.',
	'975011b2' => 'Twitch-Streamer',
	'3c103f4d' => 'Zeigt den Live-Status eines Twitch-Streamers (Spiel, Zuschauer, Titel, Vorschaubild) mit eingebettetem Player in einem Popup.',
	'1f88c31b' => 'Optionen',
	'79a32b9f' => 'Hilfe',
	'67b2d247' => 'Twitch-Benutzername',
	'71244a57' => 'Login (URL twitch.tv/<b>DEIN-LOGIN</b>), nicht der Anzeigename.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Siehe Hilfe-Tab, um diese Anmeldedaten zu generieren.',
	'41d3cbb9' => 'Stream öffnen',
	'f1c50f2d' => 'Eingebettetes Popup (Twitch-Player auf der Website)',
	'1b6c8b33' => 'Neuer Tab (twitch.tv)',
	'cc298ae3' => 'Offline anzeigen',
	'4990c8d6' => 'Immer anzeigen (mit OFFLINE-Badge)',
	'fdccaf5d' => 'Ausblenden wenn offline',
	'189cc521' => 'Client ID und Secret generieren',
	'a16d654a' => 'Melde dich auf <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> mit deinem Twitch-Konto an.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Name: <code>NeoFrag widget</code> (frei)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (für dieses Widget nicht verwendet, aber Pflichtfeld)',
	'5faa6ed1' => 'Kategorie: <code>Website Integration</code>',
	'3a798552' => 'Client-Typ: <strong>Confidential</strong>',
	'9451ddf0' => 'Erstellen → du erhältst eine <strong>Client ID</strong>',
	'cf2863ce' => 'Klicke auf die App → <strong>New Secret</strong> → kopiere das <strong>Client Secret</strong>',
	'd74ba844' => 'Füge beide in die obigen Felder ein.',
	'8c480bbb' => 'Das Widget verwendet <code>client_credentials</code>-Authentifizierung (Server-to-Server) — deine Besucher müssen sich nicht bei Twitch anmelden. Das Access-Token wird 60 Tage zwischengespeichert.',
	'4edf59a6' => 'Keine Anmeldedaten?',
	'38043231' => 'Das Widget funktioniert trotzdem: Es zeigt nur einen \'Auf Twitch ansehen\'-Button ohne Live-Status oder Stream-Details.',
	'98b98678' => 'Status nicht verfügbar (ohne API)',
	'e08bc8ce' => 'LIVE',
	'48b614a4' => 'Offline',
	'77baa327' => 'Live ansehen',
	'94d43c73' => 'Kanal ansehen',
	'8b12494a' => 'Live-Status',
	'939bf8fb' => 'Live-Status mehrerer Twitch-/YouTube-Kanäle (Spiel, Zuschauer, Titel, Vorschaubild) mit eingebettetem Player.',
	'f33d8391' => 'Live',
	'67a00f4f' => 'Konfiguriere mindestens einen Kanal im Admin-Bereich.',
	'290f6169' => 'Kanäle',
	'87906cd9' => 'Einer pro Zeile, als <code>provider:kanal</code> (z. B. <code>twitch:ninja</code>, <code>youtube:UC...</code>). Provider weggelassen = Twitch. Max. 12.',
	'5366c118' => 'Twitch-Zugangsdaten (Hilfe-Tab). Für den Status von Twitch-Kanälen erforderlich.',
	'f9d320e5' => 'YouTube-API-Schlüssel',
	'c7051a1b' => 'YouTube Data API v3-Schlüssel (Google Cloud). Für den Status von YouTube-Kanälen erforderlich. Striktes Kontingent.',
	'47a688b0' => 'Eingebettetes Popup (Player auf der Seite)',
	'767e0e64' => 'Neuer Tab (externer Kanal)',
	'367e9c23' => 'Twitch-Zugangsdaten (Client ID & Secret)',
	'868f356a' => 'Melde dich auf <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> an.',
	'1521d701' => '<strong>Applications</strong> → <strong>Register Your Application</strong> (Typ <strong>Confidential</strong>, Redirect <code>http://localhost</code>).',
	'98ec3031' => 'Kopiere die <strong>Client ID</strong> und erzeuge ein <strong>Client Secret</strong>; füge beides oben ein.',
	'85996f6c' => '<code>client_credentials</code>-Auth (Server-zu-Server) — deine Besucher müssen sich nicht anmelden; das Token wird zwischengespeichert.',
	'88835a36' => 'Aktiviere in der <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a> die <strong>YouTube Data API v3</strong>.',
	'f7e50b21' => 'Erstelle einen <strong>API-Schlüssel</strong> (Anmeldedaten) und füge ihn oben ein. Für den Kanal die <code>channelId</code> (UC...) verwenden.',
	'364d1ba1' => 'Ohne Zugangsdaten werden Kanäle weiterhin mit Status „nicht verfügbar" und einem Direktlink gelistet.',
	'ed9e84ae' => 'Kanal öffnen',
];
