<?php
declare(strict_types=1);

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configure the Twitch username in the admin panel.',
	'975011b2' => 'Twitch streamer',
	'3c103f4d' => 'Shows the live status of a Twitch streamer (game, viewers, title, thumbnail) with embedded player in a popup.',
	'1f88c31b' => 'Options',
	'79a32b9f' => 'Help',
	'67b2d247' => 'Twitch username',
	'71244a57' => 'Login (URL twitch.tv/<b>YOUR-LOGIN</b>), not the display name.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'See the Help tab to generate these credentials.',
	'41d3cbb9' => 'Open stream',
	'f1c50f2d' => 'Embedded popup (Twitch player on the site)',
	'1b6c8b33' => 'New tab (twitch.tv)',
	'cc298ae3' => 'Show offline',
	'4990c8d6' => 'Always show (with OFFLINE badge)',
	'fdccaf5d' => 'Hide when offline',
	'189cc521' => 'How to generate Client ID & Client Secret',
	'a16d654a' => 'Sign in to <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> with your Twitch account.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Name: <code>NeoFrag widget</code> (free)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (not used for this widget but required field)',
	'5faa6ed1' => 'Category: <code>Website Integration</code>',
	'3a798552' => 'Client type: <strong>Confidential</strong>',
	'9451ddf0' => 'Create → you get a <strong>Client ID</strong>',
	'cf2863ce' => 'Click on the app → <strong>New Secret</strong> → copy the <strong>Client Secret</strong>',
	'd74ba844' => 'Paste both into the fields above.',
	'8c480bbb' => 'The widget uses <code>client_credentials</code> auth (Server-to-Server) — no need for your visitors to log into Twitch. The access token is cached for 60 days.',
	'4edf59a6' => 'No credentials?',
	'38043231' => 'The widget still works: it will just show a \'View on Twitch\' button without live status or stream details.',
	'98b98678' => 'Status unavailable (no API)',
	'e08bc8ce' => 'LIVE',
	'48b614a4' => 'Offline',
	'77baa327' => 'Watch live',
	'94d43c73' => 'View channel',
	'8b12494a' => 'Live status',
	'939bf8fb' => 'Live status of several Twitch / YouTube channels (game, viewers, title, thumbnail) with embedded player.',
	'f33d8391' => 'Live',
	'67a00f4f' => 'Configure at least one channel in the admin panel.',
	'290f6169' => 'Channels',
	'87906cd9' => 'One per line, as <code>provider:channel</code> (e.g. <code>twitch:ninja</code>, <code>youtube:UC...</code>). Provider omitted = Twitch. Max 12.',
	'5366c118' => 'Twitch credentials (Help tab). Required for Twitch channel status.',
	'f9d320e5' => 'YouTube API key',
	'c7051a1b' => 'YouTube Data API v3 key (Google Cloud). Required for YouTube channel status. Strict quota.',
	'47a688b0' => 'Embedded popup (player on the site)',
	'767e0e64' => 'New tab (external channel)',
	'367e9c23' => 'Twitch credentials (Client ID & Secret)',
	'868f356a' => 'Sign in at <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a>.',
	'1521d701' => '<strong>Applications</strong> → <strong>Register Your Application</strong> (type <strong>Confidential</strong>, redirect <code>http://localhost</code>).',
	'98ec3031' => 'Copy the <strong>Client ID</strong> and generate a <strong>Client Secret</strong>; paste them above.',
	'85996f6c' => '<code>client_credentials</code> auth (server-to-server) — your visitors don\'t need to log in; the token is cached.',
	'88835a36' => 'On <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>, enable <strong>YouTube Data API v3</strong>.',
	'f7e50b21' => 'Create an <strong>API key</strong> (Credentials) and paste it above. For the channel, use its <code>channelId</code> (UC...).',
	'364d1ba1' => 'Without credentials, channels are still listed with an "unavailable" status and a direct link.',
];
