<?php

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configura el nombre de Twitch en el panel de administración.',
	'975011b2' => 'Streamer de Twitch',
	'3c103f4d' => 'Muestra el estado en vivo de un streamer de Twitch (juego, espectadores, título, miniatura) con reproductor integrado en un popup.',
	'1f88c31b' => 'Opciones',
	'79a32b9f' => 'Ayuda',
	'67b2d247' => 'Usuario de Twitch',
	'71244a57' => 'Login (URL twitch.tv/<b>TU-LOGIN</b>), no el nombre para mostrar.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Ve a la pestaña Ayuda para generar estas credenciales.',
	'41d3cbb9' => 'Abrir stream',
	'f1c50f2d' => 'Popup integrado (reproductor Twitch en el sitio)',
	'1b6c8b33' => 'Nueva pestaña (twitch.tv)',
	'cc298ae3' => 'Mostrar desconectado',
	'4990c8d6' => 'Mostrar siempre (con insignia OFFLINE)',
	'fdccaf5d' => 'Ocultar si está desconectado',
	'189cc521' => 'Cómo generar Client ID & Client Secret',
	'a16d654a' => 'Inicia sesión en <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> con tu cuenta de Twitch.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Nombre: <code>NeoFrag widget</code> (libre)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (no usado para este widget pero campo obligatorio)',
	'5faa6ed1' => 'Categoría: <code>Website Integration</code>',
	'3a798552' => 'Tipo de cliente: <strong>Confidential</strong>',
	'9451ddf0' => 'Crea → obtienes un <strong>Client ID</strong>',
	'cf2863ce' => 'Clic en la app → <strong>New Secret</strong> → copia el <strong>Client Secret</strong>',
	'd74ba844' => 'Pega ambos en los campos de arriba.',
	'8c480bbb' => 'El widget usa autenticación <code>client_credentials</code> (Server-to-Server) — los visitantes no necesitan iniciar sesión en Twitch. El token de acceso se guarda en caché 60 días.',
	'4edf59a6' => '¿Sin credenciales?',
	'38043231' => 'El widget sigue funcionando: solo mostrará un botón \'Ver en Twitch\' sin estado en vivo ni detalles del stream.',
	'98b98678' => 'Estado no disponible (sin API)',
	'e08bc8ce' => 'EN VIVO',
	'48b614a4' => 'Desconectado',
	'77baa327' => 'Ver en vivo',
	'94d43c73' => 'Ver canal',
];
