<?php

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configura el nombre de Twitch en el panel de administración.',
	'975011b2' => 'Streamer de Twitch',
	'3c103f4d' => 'Muestra el estado en vivo de un streamer de Twitch (juego, espectadores, título, miniatura) con reproductor integrado en un popup.',
	'1f88c31b' => 'Opciones',
	'79a32b9f' => 'Ayuda',
	'67b2d247' => 'Usuario de Twitch',
	'71244a57' => 'Login (URL twitch.tv/<b>TU-LOGIN</b>), no el nombre para mostrar.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Ve a la pestaña Ayuda para generar estas credenciales.',
	'41d3cbb9' => 'Abrir stream',
	'f1c50f2d' => 'Popup integrado (reproductor Twitch en el sitio)',
	'1b6c8b33' => 'Nueva pestaña (twitch.tv)',
	'cc298ae3' => 'Mostrar desconectado',
	'4990c8d6' => 'Mostrar siempre (con insignia OFFLINE)',
	'fdccaf5d' => 'Ocultar si está desconectado',
	'189cc521' => 'Cómo generar Client ID & Client Secret',
	'a16d654a' => 'Inicia sesión en <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> con tu cuenta de Twitch.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Nombre: <code>NeoFrag widget</code> (libre)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (no usado para este widget pero campo obligatorio)',
	'5faa6ed1' => 'Categoría: <code>Website Integration</code>',
	'3a798552' => 'Tipo de cliente: <strong>Confidential</strong>',
	'9451ddf0' => 'Crea → obtienes un <strong>Client ID</strong>',
	'cf2863ce' => 'Clic en la app → <strong>New Secret</strong> → copia el <strong>Client Secret</strong>',
	'd74ba844' => 'Pega ambos en los campos de arriba.',
	'8c480bbb' => 'El widget usa autenticación <code>client_credentials</code> (Server-to-Server) — los visitantes no necesitan iniciar sesión en Twitch. El token de acceso se guarda en caché 60 días.',
	'4edf59a6' => '¿Sin credenciales?',
	'38043231' => 'El widget sigue funcionando: solo mostrará un botón \'Ver en Twitch\' sin estado en vivo ni detalles del stream.',
	'98b98678' => 'Estado no disponible (sin API)',
	'e08bc8ce' => 'EN VIVO',
	'48b614a4' => 'Desconectado',
	'77baa327' => 'Ver en vivo',
	'94d43c73' => 'Ver canal',
	'8b12494a' => 'Estado en directo',
	'939bf8fb' => 'Estado en directo de varios canales de Twitch / YouTube (juego, espectadores, título, miniatura) con reproductor integrado.',
	'f33d8391' => 'En directo',
	'67a00f4f' => 'Configura al menos un canal en el panel de administración.',
	'290f6169' => 'Canales',
	'87906cd9' => 'Uno por línea, con formato <code>proveedor:canal</code> (ej. <code>twitch:ninja</code>, <code>youtube:UC...</code>). Proveedor omitido = Twitch. Máx. 12.',
	'5366c118' => 'Credenciales de Twitch (pestaña Ayuda). Necesarias para el estado de los canales de Twitch.',
	'f9d320e5' => 'Clave API de YouTube',
	'c7051a1b' => 'Clave de YouTube Data API v3 (Google Cloud). Necesaria para el estado de los canales de YouTube. Cuota estricta.',
	'47a688b0' => 'Popup integrada (reproductor en el sitio)',
	'767e0e64' => 'Nueva pestaña (canal externo)',
	'367e9c23' => 'Credenciales de Twitch (Client ID y Secret)',
	'868f356a' => 'Inicia sesión en <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a>.',
	'1521d701' => '<strong>Applications</strong> → <strong>Register Your Application</strong> (tipo <strong>Confidential</strong>, redirect <code>http://localhost</code>).',
	'98ec3031' => 'Copia el <strong>Client ID</strong> y genera un <strong>Client Secret</strong>; pégalos arriba.',
	'85996f6c' => 'Autenticación <code>client_credentials</code> (servidor a servidor) — tus visitantes no tienen que iniciar sesión; el token se almacena en caché.',
	'88835a36' => 'En <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>, activa <strong>YouTube Data API v3</strong>.',
	'f7e50b21' => 'Crea una <strong>clave API</strong> (Credenciales) y pégala arriba. Para el canal, usa su <code>channelId</code> (UC...).',
	'364d1ba1' => 'Sin credenciales, los canales se listan igualmente con estado «no disponible» y un enlace directo.',
];
