<?php
declare(strict_types=1);

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configura il nome Twitch nel pannello di amministrazione.',
	'975011b2' => 'Streamer Twitch',
	'3c103f4d' => 'Mostra lo stato live di uno streamer Twitch (gioco, spettatori, titolo, miniatura) con player integrato in un popup.',
	'1f88c31b' => 'Opzioni',
	'79a32b9f' => 'Aiuto',
	'67b2d247' => 'Nome utente Twitch',
	'71244a57' => 'Login (URL twitch.tv/<b>IL-TUO-LOGIN</b>), non il nome visualizzato.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Consulta la scheda Aiuto per generare queste credenziali.',
	'41d3cbb9' => 'Apri lo stream',
	'f1c50f2d' => 'Popup integrato (player Twitch sul sito)',
	'1b6c8b33' => 'Nuova scheda (twitch.tv)',
	'cc298ae3' => 'Mostra offline',
	'4990c8d6' => 'Mostra sempre (con badge OFFLINE)',
	'fdccaf5d' => 'Nascondi se offline',
	'189cc521' => 'Come generare Client ID & Client Secret',
	'a16d654a' => 'Accedi a <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> con il tuo account Twitch.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Nome: <code>NeoFrag widget</code> (libero)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (non usato per questo widget ma campo obbligatorio)',
	'5faa6ed1' => 'Categoria: <code>Website Integration</code>',
	'3a798552' => 'Tipo client: <strong>Confidential</strong>',
	'9451ddf0' => 'Crea → ottieni un <strong>Client ID</strong>',
	'cf2863ce' => 'Clic sull\'app → <strong>New Secret</strong> → copia il <strong>Client Secret</strong>',
	'd74ba844' => 'Incolla entrambi nei campi sopra.',
	'8c480bbb' => 'Il widget utilizza l\'autenticazione <code>client_credentials</code> (Server-to-Server) — i visitatori non devono accedere a Twitch. Il token di accesso viene memorizzato in cache per 60 giorni.',
	'4edf59a6' => 'Senza credenziali?',
	'38043231' => 'Il widget funziona comunque: mostrerà solo un pulsante \'Visualizza su Twitch\' senza stato live o dettagli dello stream.',
	'98b98678' => 'Stato non disponibile (senza API)',
	'e08bc8ce' => 'IN DIRETTA',
	'48b614a4' => 'Offline',
	'77baa327' => 'Guarda live',
	'94d43c73' => 'Visualizza canale',
	'8b12494a' => 'Stato live',
	'939bf8fb' => 'Stato live di più canali Twitch / YouTube (gioco, spettatori, titolo, miniatura) con lettore integrato.',
	'f33d8391' => 'Live',
	'67a00f4f' => 'Configura almeno un canale nel pannello di amministrazione.',
	'290f6169' => 'Canali',
	'87906cd9' => 'Uno per riga, nel formato <code>provider:canale</code> (es. <code>twitch:ninja</code>, <code>youtube:UC...</code>). Provider omesso = Twitch. Max 12.',
	'5366c118' => 'Credenziali Twitch (scheda Aiuto). Necessarie per lo stato dei canali Twitch.',
	'f9d320e5' => 'Chiave API YouTube',
	'c7051a1b' => 'Chiave YouTube Data API v3 (Google Cloud). Necessaria per lo stato dei canali YouTube. Quota rigida.',
	'47a688b0' => 'Popup integrato (lettore sul sito)',
	'767e0e64' => 'Nuova scheda (canale esterno)',
	'367e9c23' => 'Credenziali Twitch (Client ID & Secret)',
	'868f356a' => 'Accedi su <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a>.',
	'1521d701' => '<strong>Applications</strong> → <strong>Register Your Application</strong> (tipo <strong>Confidential</strong>, redirect <code>http://localhost</code>).',
	'98ec3031' => 'Copia il <strong>Client ID</strong> e genera un <strong>Client Secret</strong>; incollali sopra.',
	'85996f6c' => 'Auth <code>client_credentials</code> (server-to-server) — i visitatori non devono accedere; il token è in cache.',
	'88835a36' => 'Su <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>, attiva <strong>YouTube Data API v3</strong>.',
	'f7e50b21' => 'Crea una <strong>chiave API</strong> (Credenziali) e incollala sopra. Per il canale, usa il suo <code>channelId</code> (UC...).',
	'364d1ba1' => 'Senza credenziali, i canali restano elencati con stato «non disponibile» e un link diretto.',
];
