<?php

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configure o nome do Twitch no painel de administração.',
	'975011b2' => 'Streamer Twitch',
	'3c103f4d' => 'Mostra o status ao vivo de um streamer Twitch (jogo, visualizadores, título, miniatura) com player embutido em um popup.',
	'1f88c31b' => 'Opções',
	'79a32b9f' => 'Ajuda',
	'67b2d247' => 'Nome de usuário Twitch',
	'71244a57' => 'Login (URL twitch.tv/<b>SEU-LOGIN</b>), não o nome de exibição.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Veja a aba Ajuda para gerar estas credenciais.',
	'41d3cbb9' => 'Abrir stream',
	'f1c50f2d' => 'Popup integrado (player Twitch no site)',
	'1b6c8b33' => 'Nova aba (twitch.tv)',
	'cc298ae3' => 'Mostrar offline',
	'4990c8d6' => 'Sempre mostrar (com selo OFFLINE)',
	'fdccaf5d' => 'Ocultar quando offline',
	'189cc521' => 'Como gerar Client ID & Client Secret',
	'a16d654a' => 'Faça login em <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> com sua conta Twitch.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Nome: <code>NeoFrag widget</code> (livre)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (não usado para este widget mas campo obrigatório)',
	'5faa6ed1' => 'Categoria: <code>Website Integration</code>',
	'3a798552' => 'Tipo de cliente: <strong>Confidential</strong>',
	'9451ddf0' => 'Cria → você recebe um <strong>Client ID</strong>',
	'cf2863ce' => 'Clique no app → <strong>New Secret</strong> → copie o <strong>Client Secret</strong>',
	'd74ba844' => 'Cole ambos nos campos acima.',
	'8c480bbb' => 'O widget usa autenticação <code>client_credentials</code> (Server-to-Server) — os visitantes não precisam fazer login no Twitch. O token de acesso é armazenado em cache por 60 dias.',
	'4edf59a6' => 'Sem credenciais?',
	'38043231' => 'O widget ainda funciona: apenas mostrará um botão \'Ver no Twitch\' sem status ao vivo ou detalhes do stream.',
	'98b98678' => 'Status indisponível (sem API)',
	'e08bc8ce' => 'AO VIVO',
	'48b614a4' => 'Offline',
	'77baa327' => 'Assistir ao vivo',
	'94d43c73' => 'Ver canal',
];
