<?php
declare(strict_types=1);

return [
	'75407e96' => 'Twitch',
	'3d474ce7' => 'Configure o nome do Twitch no painel de administração.',
	'975011b2' => 'Streamer Twitch',
	'3c103f4d' => 'Mostra o status ao vivo de um streamer Twitch (jogo, visualizadores, título, miniatura) com player embutido em um popup.',
	'1f88c31b' => 'Opções',
	'79a32b9f' => 'Ajuda',
	'67b2d247' => 'Nome de usuário Twitch',
	'71244a57' => 'Login (URL twitch.tv/<b>SEU-LOGIN</b>), não o nome de exibição.',
	'6a5dc085' => 'Client ID',
	'a7f64d57' => 'Client Secret',
	'c7a196be' => 'Veja a aba Ajuda para gerar estas credenciais.',
	'41d3cbb9' => 'Abrir stream',
	'f1c50f2d' => 'Popup integrado (player Twitch no site)',
	'1b6c8b33' => 'Nova aba (twitch.tv)',
	'cc298ae3' => 'Mostrar offline',
	'4990c8d6' => 'Sempre mostrar (com selo OFFLINE)',
	'fdccaf5d' => 'Ocultar quando offline',
	'189cc521' => 'Como gerar Client ID & Client Secret',
	'a16d654a' => 'Faça login em <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a> com sua conta Twitch.',
	'c38842df' => '<strong>Applications</strong> → <strong>Register Your Application</strong>.',
	'de196c6b' => 'Nome: <code>NeoFrag widget</code> (livre)',
	'81271a2f' => 'OAuth Redirect URLs: <code>http://localhost</code> (não usado para este widget mas campo obrigatório)',
	'5faa6ed1' => 'Categoria: <code>Website Integration</code>',
	'3a798552' => 'Tipo de cliente: <strong>Confidential</strong>',
	'9451ddf0' => 'Cria → você recebe um <strong>Client ID</strong>',
	'cf2863ce' => 'Clique no app → <strong>New Secret</strong> → copie o <strong>Client Secret</strong>',
	'd74ba844' => 'Cole ambos nos campos acima.',
	'8c480bbb' => 'O widget usa autenticação <code>client_credentials</code> (Server-to-Server) — os visitantes não precisam fazer login no Twitch. O token de acesso é armazenado em cache por 60 dias.',
	'4edf59a6' => 'Sem credenciais?',
	'38043231' => 'O widget ainda funciona: apenas mostrará um botão \'Ver no Twitch\' sem status ao vivo ou detalhes do stream.',
	'98b98678' => 'Status indisponível (sem API)',
	'e08bc8ce' => 'AO VIVO',
	'48b614a4' => 'Offline',
	'77baa327' => 'Assistir ao vivo',
	'94d43c73' => 'Ver canal',
	'8b12494a' => 'Estado ao vivo',
	'939bf8fb' => 'Estado ao vivo de vários canais Twitch / YouTube (jogo, espectadores, título, miniatura) com leitor integrado.',
	'f33d8391' => 'Ao vivo',
	'67a00f4f' => 'Configura pelo menos um canal no painel de administração.',
	'290f6169' => 'Canais',
	'87906cd9' => 'Um por linha, no formato <code>provider:canal</code> (ex. <code>twitch:ninja</code>, <code>youtube:UC...</code>). Provider omitido = Twitch. Máx. 12.',
	'5366c118' => 'Credenciais Twitch (separador Ajuda). Necessárias para o estado dos canais Twitch.',
	'f9d320e5' => 'Chave API YouTube',
	'c7051a1b' => 'Chave YouTube Data API v3 (Google Cloud). Necessária para o estado dos canais YouTube. Quota rígida.',
	'47a688b0' => 'Popup integrada (leitor no site)',
	'767e0e64' => 'Novo separador (canal externo)',
	'367e9c23' => 'Credenciais Twitch (Client ID & Secret)',
	'868f356a' => 'Inicia sessão em <a href="https://dev.twitch.tv/console" target="_blank" rel="noopener">dev.twitch.tv/console</a>.',
	'1521d701' => '<strong>Applications</strong> → <strong>Register Your Application</strong> (tipo <strong>Confidential</strong>, redirect <code>http://localhost</code>).',
	'98ec3031' => 'Copia o <strong>Client ID</strong> e gera um <strong>Client Secret</strong>; cola-os acima.',
	'85996f6c' => 'Auth <code>client_credentials</code> (servidor-a-servidor) — os visitantes não precisam de iniciar sessão; o token fica em cache.',
	'88835a36' => 'Na <a href="https://console.cloud.google.com/" target="_blank" rel="noopener">Google Cloud Console</a>, ativa <strong>YouTube Data API v3</strong>.',
	'f7e50b21' => 'Cria uma <strong>chave API</strong> (Credenciais) e cola-a acima. Para o canal, usa o seu <code>channelId</code> (UC...).',
	'364d1ba1' => 'Sem credenciais, os canais continuam listados com estado «indisponível» e uma ligação direta.',
];
