<?php
return [
	// i18n 2026-06-11 (code strings)
	'7cbecb62' => 'Diapositivas del widget slider',
	'90929d07' => 'Añadir una diapositiva',
	'88b2dd85' => 'Editar la diapositiva',
	'b856cdf2' => 'Nueva diapositiva',
	'bf6c25a7' => 'Diapositivas',
	'dfbc18d8' => 'Subir una imagen',
	'cc2c69bd' => 'JPEG, PNG, GIF o WebP — máx. %d MB. Si subes una imagen, el campo «URL de la imagen» se reemplazará por la ruta de la imagen subida.',
	'1816ee07' => 'Formato no permitido. Usa JPEG, PNG, GIF o WebP.',
	'b3371c67' => '— o URL de la imagen (alternativa a la subida)',
	'dd11e34f' => 'Si no subes nada, pega aquí una ruta interna (ej. <code>upload/slider/img.jpg</code>) o una URL externa completa.',
	'7449c129' => 'Se muestra en negrita encima del subtítulo.',
	'eabd0387' => 'Subtítulo / texto',
	'b04a0c0b' => 'URL a la que apunta la diapositiva al hacer clic. Déjalo en blanco si no es clicable.',
	'4a5bfde2' => 'Diapositiva activa (de lo contrario no se muestra en el widget)',
	'43c4b667' => 'Debes subir una imagen o proporcionar una URL',
	'57be4f49' => 'Diapositiva modificada',
	'30efe68b' => 'Diapositiva añadida',
	'fd4f5a56' => 'Diapositiva eliminada',
	'a49e3372' => 'Diapositiva %s',
	'580c36f1' => 'activada',
	'c987ecfa' => 'desactivada',
	'9ad200dd' => 'Orden actualizado',
	'25de8e0d' => 'Gestión de las diapositivas del widget slider en la página de inicio. Añade/edita imágenes, títulos, subtítulos, enlaces y orden.',
	'303f1e65' => 'Gestionar diapositivas',
	'65803d70' => 'Ninguna diapositiva por el momento.',
	'e618c048' => 'El widget slider mostrará un marcador por defecto hasta que se añada una diapositiva.',
	'16b0885d' => 'Crear la primera diapositiva',
	'72d49291' => 'Título / Subtítulo',
	'05001b8b' => 'Enlace',
	'7b0b30fa' => 'Sin imagen',
	'a84f139c' => '(sin título)',
	'aa7a6e6a' => '¿Confirmar la eliminación de esta diapositiva?',
	'3ff2b02c' => 'Arrastra las filas para reordenar, luego haz clic en «Guardar orden».',
	'a3d90926' => 'Guardar orden',
];
