<?php
return [
	// i18n 2026-06-11 (code strings)
	'7cbecb62' => 'Slide del widget slider',
	'90929d07' => 'Aggiungi una slide',
	'88b2dd85' => 'Modifica la slide',
	'b856cdf2' => 'Nuova slide',
	'bf6c25a7' => 'Slide',
	'dfbc18d8' => 'Carica un\'immagine',
	'cc2c69bd' => 'JPEG, PNG, GIF o WebP — max %d MB. Se carichi, il campo «URL dell\'immagine» verrà sostituito dal percorso dell\'immagine caricata.',
	'1816ee07' => 'Formato non consentito. Usa JPEG, PNG, GIF o WebP.',
	'b3371c67' => '— o URL dell\'immagine (alternativa al caricamento)',
	'dd11e34f' => 'Se non carichi nulla, incolla qui un percorso interno (es. <code>upload/slider/img.jpg</code>) o un URL esterno completo.',
	'7449c129' => 'Mostrato in grassetto sopra il sottotitolo.',
	'eabd0387' => 'Sottotitolo / testo',
	'b04a0c0b' => 'URL a cui punta la slide al clic. Lascia vuoto se la slide non è cliccabile.',
	'4a5bfde2' => 'Slide attiva (altrimenti non mostrata nel widget)',
	'43c4b667' => 'Devi caricare un\'immagine o fornire un URL',
	'57be4f49' => 'Slide modificata',
	'30efe68b' => 'Slide aggiunta',
	'fd4f5a56' => 'Slide eliminata',
	'a49e3372' => 'Slide %s',
	'580c36f1' => 'attivata',
	'c987ecfa' => 'disattivata',
	'9ad200dd' => 'Ordine aggiornato',
	'25de8e0d' => 'Gestione delle slide del widget slider nella home page. Aggiungi/modifica immagini, titoli, sottotitoli, link e ordine.',
	'303f1e65' => 'Gestisci le slide',
	'65803d70' => 'Nessuna slide per il momento.',
	'e618c048' => 'Il widget slider mostrerà un segnaposto predefinito finché non viene aggiunta una slide.',
	'16b0885d' => 'Crea la prima slide',
	'72d49291' => 'Titolo / Sottotitolo',
	'05001b8b' => 'Link',
	'7b0b30fa' => 'Nessuna immagine',
	'a84f139c' => '(senza titolo)',
	'aa7a6e6a' => 'Confermare l\'eliminazione di questa slide?',
	'3ff2b02c' => 'Trascina le righe per riordinare, poi clicca «Salva ordine».',
	'a3d90926' => 'Salva ordine',
];
