<?php
return [
	// i18n 2026-06-11 (code strings)
	'7cbecb62' => 'Slides do widget slider',
	'90929d07' => 'Adicionar um slide',
	'88b2dd85' => 'Editar o slide',
	'b856cdf2' => 'Novo slide',
	'bf6c25a7' => 'Slides',
	'dfbc18d8' => 'Enviar uma imagem',
	'cc2c69bd' => 'JPEG, PNG, GIF ou WebP — máx. %d MB. Se enviares, o campo «URL da imagem» será substituído pelo caminho da imagem enviada.',
	'1816ee07' => 'Formato não permitido. Usa JPEG, PNG, GIF ou WebP.',
	'b3371c67' => '— ou URL da imagem (alternativa ao envio)',
	'dd11e34f' => 'Se não enviares nada, cola aqui um caminho interno (ex. <code>upload/slider/img.jpg</code>) ou um URL externo completo.',
	'7449c129' => 'Apresentado a negrito acima do subtítulo.',
	'eabd0387' => 'Subtítulo / texto',
	'b04a0c0b' => 'URL para onde o slide aponta ao clicar. Deixa em branco se o slide não for clicável.',
	'4a5bfde2' => 'Slide ativo (caso contrário não é apresentado no widget)',
	'43c4b667' => 'Tens de enviar uma imagem ou fornecer um URL',
	'57be4f49' => 'Slide modificado',
	'30efe68b' => 'Slide adicionado',
	'fd4f5a56' => 'Slide eliminado',
	'a49e3372' => 'Slide %s',
	'580c36f1' => 'ativada',
	'c987ecfa' => 'desativada',
	'9ad200dd' => 'Ordem atualizada',
	'25de8e0d' => 'Gestão dos slides do widget slider na página inicial. Adiciona/edita imagens, títulos, subtítulos, ligações e ordem.',
	'303f1e65' => 'Gerir os slides',
	'65803d70' => 'Nenhum slide de momento.',
	'e618c048' => 'O widget slider apresentará um marcador predefinido até que um slide seja adicionado.',
	'16b0885d' => 'Criar o primeiro slide',
	'72d49291' => 'Título / Subtítulo',
	'05001b8b' => 'Ligação',
	'7b0b30fa' => 'Sem imagem',
	'a84f139c' => '(sem título)',
	'aa7a6e6a' => 'Confirmar a eliminação deste slide?',
	'3ff2b02c' => 'Arrasta as linhas para reordenar, depois clica «Guardar ordem».',
	'a3d90926' => 'Guardar ordem',
];
