<?php
declare(strict_types=1);

return [
	'9f6837b7' => 'TeamSpeak 3 Server',
	'bac4720e' => 'Zeigt Kanäle und Clients, die mit einem TeamSpeak 3-Server verbunden sind, mit einem \'Verbinden\'-Button.',
	'34010fa4' => 'TeamSpeak',
	'951582f0' => 'Konfiguriere die TS3-Serveradresse im Admin-Bereich.',
	'932a46fc' => 'Verbindung fehlgeschlagen.',
	'cc42d6c7' => 'TeamSpeak beitreten',
	'1f88c31b' => 'Optionen',
	'79a32b9f' => 'Hilfe',
	'37f8e895' => 'Modus',
	'1a3032cd' => 'Einfach (Karte + Beitreten-Button)',
	'd6824680' => 'Baum (Kanäle + Clients in Echtzeit)',
	'cde5ca1a' => 'Serveradresse',
	'502b1ca3' => 'Sprach-Port',
	'7a903f80' => 'Standard: 9987',
	'6d6cf1e7' => 'Benutzerdefinierter Titel',
	'71e8c00c' => 'Optional: ersetzt den Servernamen',
	'2445659b' => 'Baum-Modus — ServerQuery erforderlich',
	'20f0248e' => 'Um Kanäle & Clients anzuzeigen, verbindet sich das Widget mit ServerQuery (TCP, Standard-Port 10011). Du musst ein dediziertes Query-Konto auf deinem TS3-Server erstellen (TSDNS-Befehl: <code>serverqueryadd client_login_name=neofrag_viewer client_login_password=…</code>).',
	'85eb1a62' => 'ServerQuery-Port',
	'7b2f0edd' => 'Standard: 10011',
	'f76e4fdf' => 'Query-Benutzer',
	'50de38c2' => 'Query-Passwort',
	'47732ac4' => 'Anzeigemodi',
	'c6d73834' => 'Einfach',
	'59a56f2d' => 'Basis-Karte mit Servername und \'Beitreten\'-Button (<code>ts3server://</code>-Link). Keine Authentifizierung erforderlich. Empfohlen für eine einfache Verknüpfung.',
	'79f3870f' => 'Baum',
	'7cffba77' => 'Zeigt Kanäle und verbundene Clients in Echtzeit über ServerQuery. Erfordert ein Query-Konto auf dem TS3-Server. Port 10011 muss vom Webserver erreichbar sein.',
	'cc413b44' => 'ServerQuery-Konto erstellen',
	'16ea05df' => 'Verbinde dich als Admin über den Client mit deinem TS3.',
	'ea11cf85' => 'Tools → ServerQuery Login → gib einen Namen ein (z.B. <code>neofrag_viewer</code>) und kopiere das generierte Passwort.',
	'eb9c9a62' => 'Port 10011 (TCP) muss von deinem Webhosting geöffnet sein. Andernfalls bleibe im \'Einfach\'-Modus.',
	'00c82e74' => 'Clients',
];
