<?php
declare(strict_types=1);

return [
	'9f6837b7' => 'TeamSpeak 3 server',
	'bac4720e' => 'Shows channels and clients connected to a TeamSpeak 3 server, with a \'Connect\' button.',
	'34010fa4' => 'TeamSpeak',
	'951582f0' => 'Configure the TS3 server address in the admin panel.',
	'932a46fc' => 'Connection failed.',
	'cc42d6c7' => 'Join TeamSpeak',
	'1f88c31b' => 'Options',
	'79a32b9f' => 'Help',
	'37f8e895' => 'Mode',
	'1a3032cd' => 'Simple (card + join button)',
	'd6824680' => 'Tree (channels + clients in real time)',
	'cde5ca1a' => 'Server address',
	'502b1ca3' => 'Voice port',
	'7a903f80' => 'Default: 9987',
	'6d6cf1e7' => 'Custom title',
	'71e8c00c' => 'Optional: replaces the server name',
	'2445659b' => 'Tree mode — ServerQuery required',
	'20f0248e' => 'To show channels & clients, the widget connects to ServerQuery (TCP, default port 10011). You must create a dedicated query account on your TS3 server (TSDNS command: <code>serverqueryadd client_login_name=neofrag_viewer client_login_password=…</code>).',
	'85eb1a62' => 'ServerQuery port',
	'7b2f0edd' => 'Default: 10011',
	'f76e4fdf' => 'Query user',
	'50de38c2' => 'Query password',
	'47732ac4' => 'Display modes',
	'c6d73834' => 'Simple',
	'59a56f2d' => 'Basic card with server name and \'Join\' button (<code>ts3server://</code> link). No authentication required. Recommended if you just want a shortcut.',
	'79f3870f' => 'Tree',
	'7cffba77' => 'Shows channels and connected clients in real time via ServerQuery. Requires a query account on the TS3 server. Port 10011 must be reachable from the web server.',
	'cc413b44' => 'Create ServerQuery account',
	'16ea05df' => 'Connect to your TS3 as admin via the client.',
	'ea11cf85' => 'Tools → ServerQuery Login → enter a name (e.g. <code>neofrag_viewer</code>) and copy the generated password.',
	'eb9c9a62' => 'Port 10011 (TCP) must be open from your web hosting. If not, stay in \'Simple\' mode.',
	'00c82e74' => 'clients',
];
