<?php
declare(strict_types=1);

return [
	'9f6837b7' => 'Servidor TeamSpeak 3',
	'bac4720e' => 'Muestra los canales y clientes conectados a un servidor TeamSpeak 3, con un botón \'Conectar\'.',
	'34010fa4' => 'TeamSpeak',
	'951582f0' => 'Configura la dirección del servidor TS3 en el panel de administración.',
	'932a46fc' => 'Conexión imposible.',
	'cc42d6c7' => 'Unirse a TeamSpeak',
	'1f88c31b' => 'Opciones',
	'79a32b9f' => 'Ayuda',
	'37f8e895' => 'Modo',
	'1a3032cd' => 'Simple (tarjeta + botón unirse)',
	'd6824680' => 'Árbol (canales + clientes en tiempo real)',
	'cde5ca1a' => 'Dirección del servidor',
	'502b1ca3' => 'Puerto de voz',
	'7a903f80' => 'Por defecto: 9987',
	'6d6cf1e7' => 'Título personalizado',
	'71e8c00c' => 'Opcional: reemplaza el nombre del servidor',
	'2445659b' => 'Modo árbol — ServerQuery requerido',
	'20f0248e' => 'Para mostrar canales y clientes, el widget se conecta a ServerQuery (TCP, puerto 10011 por defecto). Debes crear una cuenta query dedicada en tu servidor TS3.',
	'85eb1a62' => 'Puerto ServerQuery',
	'7b2f0edd' => 'Por defecto: 10011',
	'f76e4fdf' => 'Usuario Query',
	'50de38c2' => 'Contraseña Query',
	'47732ac4' => 'Modos de visualización',
	'c6d73834' => 'Simple',
	'59a56f2d' => 'Tarjeta básica con nombre del servidor y botón \'Unirse\' (enlace <code>ts3server://</code>). Sin autenticación. Recomendado si solo quieres un acceso directo.',
	'79f3870f' => 'Árbol',
	'7cffba77' => 'Muestra los canales y los clientes conectados en tiempo real a través de ServerQuery. Requiere una cuenta query en el servidor TS3. El puerto 10011 debe ser accesible desde el servidor web.',
	'cc413b44' => 'Crear cuenta ServerQuery',
	'16ea05df' => 'Conéctate a tu TS3 como administrador a través del cliente.',
	'ea11cf85' => 'Herramientas → ServerQuery Login → introduce un nombre (ej: <code>neofrag_viewer</code>) y copia la contraseña generada.',
	'eb9c9a62' => 'El puerto 10011 (TCP) debe estar abierto desde tu hosting web. Si no, mantente en modo \'Simple\'.',
	'00c82e74' => 'clientes',
];
