<?php

return [
	'9f6837b7' => 'Server TeamSpeak 3',
	'bac4720e' => 'Mostra canali e client connessi a un server TeamSpeak 3, con un pulsante \'Connetti\'.',
	'34010fa4' => 'TeamSpeak',
	'951582f0' => 'Configura l\'indirizzo del server TS3 nel pannello di amministrazione.',
	'932a46fc' => 'Connessione impossibile.',
	'cc42d6c7' => 'Unisciti a TeamSpeak',
	'1f88c31b' => 'Opzioni',
	'79a32b9f' => 'Aiuto',
	'37f8e895' => 'Modalità',
	'1a3032cd' => 'Semplice (scheda + pulsante per unirsi)',
	'd6824680' => 'Albero (canali + client in tempo reale)',
	'cde5ca1a' => 'Indirizzo del server',
	'502b1ca3' => 'Porta voce',
	'7a903f80' => 'Predefinito: 9987',
	'6d6cf1e7' => 'Titolo personalizzato',
	'71e8c00c' => 'Opzionale: sostituisce il nome del server',
	'2445659b' => 'Modalità ad albero — ServerQuery richiesto',
	'20f0248e' => 'Per mostrare canali e client, il widget si collega a ServerQuery (TCP, porta predefinita 10011). Devi creare un account query dedicato sul tuo server TS3.',
	'85eb1a62' => 'Porta ServerQuery',
	'7b2f0edd' => 'Predefinito: 10011',
	'f76e4fdf' => 'Utente Query',
	'50de38c2' => 'Password Query',
	'47732ac4' => 'Modalità di visualizzazione',
	'c6d73834' => 'Semplice',
	'59a56f2d' => 'Scheda di base con nome del server e pulsante \'Unisciti\' (link <code>ts3server://</code>). Nessuna autenticazione richiesta. Consigliato se vuoi solo un collegamento.',
	'79f3870f' => 'Albero',
	'7cffba77' => 'Mostra canali e client connessi in tempo reale tramite ServerQuery. Richiede un account query sul server TS3. La porta 10011 deve essere accessibile dal server web.',
	'cc413b44' => 'Crea account ServerQuery',
	'16ea05df' => 'Collegati al tuo TS3 come admin tramite il client.',
	'ea11cf85' => 'Strumenti → ServerQuery Login → inserisci un nome (es: <code>neofrag_viewer</code>) e copia la password generata.',
	'eb9c9a62' => 'La porta 10011 (TCP) deve essere aperta dal tuo hosting web. In caso contrario, resta in modalità \'Semplice\'.',
	'00c82e74' => 'client',
];
