<?php
declare(strict_types=1);

return [
	'9f6837b7' => 'Servidor TeamSpeak 3',
	'bac4720e' => 'Mostra canais e clientes conectados a um servidor TeamSpeak 3, com um botão \'Conectar\'.',
	'34010fa4' => 'TeamSpeak',
	'951582f0' => 'Configure o endereço do servidor TS3 no painel de administração.',
	'932a46fc' => 'Conexão impossível.',
	'cc42d6c7' => 'Entrar no TeamSpeak',
	'1f88c31b' => 'Opções',
	'79a32b9f' => 'Ajuda',
	'37f8e895' => 'Modo',
	'1a3032cd' => 'Simples (cartão + botão entrar)',
	'd6824680' => 'Árvore (canais + clientes em tempo real)',
	'cde5ca1a' => 'Endereço do servidor',
	'502b1ca3' => 'Porta de voz',
	'7a903f80' => 'Padrão: 9987',
	'6d6cf1e7' => 'Título personalizado',
	'71e8c00c' => 'Opcional: substitui o nome do servidor',
	'2445659b' => 'Modo árvore — ServerQuery necessário',
	'20f0248e' => 'Para mostrar canais e clientes, o widget se conecta ao ServerQuery (TCP, porta padrão 10011). Você deve criar uma conta query dedicada no seu servidor TS3 (comando TSDNS: <code>serverqueryadd client_login_name=neofrag_viewer client_login_password=…</code>).',
	'85eb1a62' => 'Porta ServerQuery',
	'7b2f0edd' => 'Padrão: 10011',
	'f76e4fdf' => 'Usuário Query',
	'50de38c2' => 'Senha Query',
	'47732ac4' => 'Modos de exibição',
	'c6d73834' => 'Simples',
	'59a56f2d' => 'Cartão básico com nome do servidor e botão \'Entrar\' (link <code>ts3server://</code>). Sem autenticação. Recomendado se você só quer um atalho.',
	'79f3870f' => 'Árvore',
	'7cffba77' => 'Mostra canais e clientes conectados em tempo real via ServerQuery. Requer uma conta query no servidor TS3. A porta 10011 deve estar acessível pelo servidor web.',
	'cc413b44' => 'Criar conta ServerQuery',
	'16ea05df' => 'Conecte-se ao seu TS3 como admin através do cliente.',
	'ea11cf85' => 'Ferramentas → ServerQuery Login → digite um nome (ex: <code>neofrag_viewer</code>) e copie a senha gerada.',
	'eb9c9a62' => 'A porta 10011 (TCP) deve estar aberta no seu hosting web. Caso contrário, permaneça no modo \'Simples\'.',
	'00c82e74' => 'clientes',
];
