<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (de)
 */

return [
	'02f6b476' => 'Autor',
	'037b7df2' => 'Keine Abonnenten.',
	'06fdbe1b' => 'Anmeldung bestätigt! Du erhältst zukünftige Newsletter an <strong>%s</strong>.',
	'0aac9844' => 'Datum',
	'0e064b5e' => 'Melde dich für den Newsletter an, um Updates direkt per E-Mail zu erhalten.',
	'14adda10' => 'Abonnenten verwalten',
	'16679980' => 'Um deine Anmeldung zu bestätigen, klicke auf den Button unten:',
	'180c83ba' => 'Verwalte deine Abonnentenliste und den Kampagnenversand. Double-Opt-in ist aktiviert: Abonnenten müssen per E-Mail bestätigen, bevor sie in deinen Kampagnen erscheinen.',
	'1f0aec47' => 'Anmeldung bestätigen',
	'2008a6f2' => 'Anmeldedatum',
	'26535370' => 'E-Mail',
	'31d88618' => 'Newsletter',
	'361b67f5' => 'Diesen Abonnenten löschen?',
	'3d3a71d9' => 'Bestätigungs-E-Mail gesendet an %s',
	'526e2d7b' => 'Diese E-Mail-Adresse hat bereits eine Anmeldung angefragt. Prüfe dein Postfach auf den Bestätigungslink.',
	'56dca9ce' => 'Newsletter-Bestätigung',
	'573ff81d' => 'Bestätigt',
	'6105648e' => 'Verfassen',
	'6335835b' => 'Inhalt (HTML)',
	'65bdf3ec' => 'Kampagne an %d Abonnenten gesendet.',
	'7fd41a45' => 'Ausstehend',
	'85d740f8' => 'Diese E-Mail-Adresse ist bereits für den Newsletter angemeldet.',
	'8afe3630' => 'Bestätigte Abonnenten',
	'8cb61d4a' => 'Hallo,',
	'8d9ef7a4' => 'Löschen',
	'9da30cd1' => 'Abmelden',
	'a1442451' => 'Kampagnen-Verlauf',
	'a29c9965' => 'Neue Kampagne',
	'a2e2d63c' => 'Verlauf',
	'a3134b9d' => 'Wenn du diese Anfrage nicht gestellt hast, ignoriere diese E-Mail.',
	'b5ad91ec' => 'Double-Opt-in nicht bestätigt',
	'b68fdf69' => 'Empfänger',
	'b6d15296' => 'Anmelden',
	'bca59417' => 'HTML erlaubt. Ein Abmeldelink wird automatisch hinzugefügt.',
	'bd45bb7a' => 'Abonnenten',
	'c06ad4f3' => 'E-Mail bereits bestätigt. Du bist für den Newsletter angemeldet.',
	'c1d8f9a3' => 'E-Mail-Adresse',
	'c3792c02' => 'Newsletter-Abonnenten',
	'c55f374f' => 'Abonnent gelöscht.',
	'c6e0ee98' => 'Kampagnen-Verlauf',
	'caf5c873' => 'Aktionen',
	'cd539fe1' => 'Du erhältst diese E-Mail, weil du den Newsletter von %s abonniert hast.',
	'cea5b394' => 'An %d bestätigte(n) Abonnenten senden',
	'cec4ef4d' => 'Versendete Kampagnen',
	'd38f95dd' => 'Betreff',
	'dbbd5005' => 'Abmeldung',
	'e2c8f589' => 'Status',
	'ea284657' => 'Kampagnen senden',
	'edfc132e' => 'Bestätige deine Newsletter-Anmeldung — %s',
	'eee18abf' => 'Du wurdest vom Newsletter abgemeldet. <strong>%s</strong> erhält keine Newsletter mehr.',
	'efd27699' => 'Betreff',
	'f4d13508' => 'Bisher keine Kampagne gesendet.',
	'f6f03446' => 'Newsletter verfassen',
	'f705dfc0' => 'Du hast die Anmeldung zum Newsletter von <strong>%s</strong> mit der E-Mail <code>%s</code> angefragt.',
	'056af2ff' => 'Newsletter-Anmeldung (Double Opt-in) und Kampagnenversand.',
];
