<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (en)
 */

return [
	'02f6b476' => 'Author',
	'037b7df2' => 'No subscriber.',
	'06fdbe1b' => 'Subscription confirmed! You will receive future newsletters at <strong>%s</strong>.',
	'0aac9844' => 'Date',
	'0e064b5e' => 'Subscribe to the newsletter to get site updates straight to your inbox.',
	'14adda10' => 'Manage subscribers',
	'16679980' => 'To confirm your subscription, click the button below:',
	'180c83ba' => 'Manage your subscriber list and campaign sending. Double opt-in is enabled: subscribers must confirm via email before appearing in your campaigns.',
	'1f0aec47' => 'Confirm my subscription',
	'2008a6f2' => 'Subscription date',
	'26535370' => 'Email',
	'31d88618' => 'Newsletter',
	'361b67f5' => 'Delete this subscriber?',
	'3d3a71d9' => 'Confirmation email sent to %s',
	'526e2d7b' => 'This email has already requested subscription. Check your inbox for the confirmation link.',
	'56dca9ce' => 'Newsletter confirmation',
	'573ff81d' => 'Confirmed',
	'6105648e' => 'Compose',
	'6335835b' => 'Content (HTML)',
	'65bdf3ec' => 'Campaign sent to %d subscriber(s).',
	'7fd41a45' => 'Pending',
	'85d740f8' => 'This email is already subscribed to the newsletter.',
	'8afe3630' => 'Confirmed subscribers',
	'8cb61d4a' => 'Hello,',
	'8d9ef7a4' => 'Delete',
	'9da30cd1' => 'Unsubscribe',
	'a1442451' => 'Campaigns history',
	'a29c9965' => 'New campaign',
	'a2e2d63c' => 'History',
	'a3134b9d' => 'If you are not the source of this request, please ignore this email.',
	'b5ad91ec' => 'double opt-in not confirmed',
	'b68fdf69' => 'Recipients',
	'b6d15296' => 'Subscribe',
	'bca59417' => 'HTML allowed. An unsubscribe link will be added automatically.',
	'bd45bb7a' => 'Subscribers',
	'c06ad4f3' => 'Email already confirmed. You are subscribed to the newsletter.',
	'c1d8f9a3' => 'Email address',
	'c3792c02' => 'Newsletter subscribers',
	'c55f374f' => 'Subscriber deleted.',
	'c6e0ee98' => 'Campaign history',
	'caf5c873' => 'Actions',
	'cd539fe1' => 'You are receiving this email because you are subscribed to the newsletter of %s.',
	'cea5b394' => 'Send to %d confirmed subscriber(s)',
	'cec4ef4d' => 'Sent campaigns',
	'd38f95dd' => 'Subject',
	'dbbd5005' => 'Unsubscribe',
	'e2c8f589' => 'Status',
	'ea284657' => 'Send campaigns',
	'edfc132e' => 'Confirm your newsletter subscription — %s',
	'eee18abf' => 'You have been unsubscribed from the newsletter. <strong>%s</strong> will no longer receive newsletters.',
	'efd27699' => 'Subject',
	'f4d13508' => 'No campaign sent yet.',
	'f6f03446' => 'Compose a newsletter',
	'f705dfc0' => 'You requested to subscribe to the newsletter of <strong>%s</strong> with the email <code>%s</code>.',
	'056af2ff' => 'Newsletter signup (double opt-in) and campaign sending.',
];
