<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (es)
 */

return [
	'02f6b476' => 'Autor',
	'037b7df2' => 'Sin suscriptores.',
	'06fdbe1b' => '¡Suscripción confirmada! Recibirás los próximos boletines en <strong>%s</strong>.',
	'0aac9844' => 'Fecha',
	'0e064b5e' => 'Suscríbete al boletín para recibir las novedades del sitio directamente por correo.',
	'14adda10' => 'Gestionar suscriptores',
	'16679980' => 'Para confirmar tu suscripción, haz clic en el botón siguiente:',
	'180c83ba' => 'Gestiona tu lista de suscriptores y el envío de campañas. El doble opt-in está activado: los suscriptores deben confirmar por correo antes de aparecer en tus campañas.',
	'1f0aec47' => 'Confirmar mi suscripción',
	'2008a6f2' => 'Fecha de suscripción',
	'26535370' => 'Correo',
	'31d88618' => 'Boletín',
	'361b67f5' => '¿Eliminar este suscriptor?',
	'3d3a71d9' => 'Correo de confirmación enviado a %s',
	'526e2d7b' => 'Este correo ya ha solicitado la suscripción. Comprueba tu bandeja de entrada para el enlace de confirmación.',
	'56dca9ce' => 'Confirmación de boletín',
	'573ff81d' => 'Confirmado',
	'6105648e' => 'Redactar',
	'6335835b' => 'Contenido (HTML)',
	'65bdf3ec' => 'Campaña enviada a %d suscriptor(es).',
	'7fd41a45' => 'Pendiente',
	'85d740f8' => 'Este correo ya está suscrito al boletín.',
	'8afe3630' => 'Suscriptores confirmados',
	'8cb61d4a' => 'Hola,',
	'8d9ef7a4' => 'Eliminar',
	'9da30cd1' => 'Cancelar suscripción',
	'a1442451' => 'Historial de campañas',
	'a29c9965' => 'Nueva campaña',
	'a2e2d63c' => 'Historial',
	'a3134b9d' => 'Si no has originado esta solicitud, ignora este correo.',
	'b5ad91ec' => 'doble opt-in no confirmado',
	'b68fdf69' => 'Destinatarios',
	'b6d15296' => 'Suscribirse',
	'bca59417' => 'HTML permitido. Se añadirá automáticamente un enlace de baja.',
	'bd45bb7a' => 'Suscriptores',
	'c06ad4f3' => 'Correo ya confirmado. Estás suscrito al boletín.',
	'c1d8f9a3' => 'Dirección de correo',
	'c3792c02' => 'Suscriptores del boletín',
	'c55f374f' => 'Suscriptor eliminado.',
	'c6e0ee98' => 'Historial de las campañas',
	'caf5c873' => 'Acciones',
	'cd539fe1' => 'Recibes este correo porque estás suscrito al boletín de %s.',
	'cea5b394' => 'Enviar a %d suscriptor(es) confirmado(s)',
	'cec4ef4d' => 'Campañas enviadas',
	'd38f95dd' => 'Asunto',
	'dbbd5005' => 'Cancelar suscripción',
	'e2c8f589' => 'Estado',
	'ea284657' => 'Enviar campañas',
	'edfc132e' => 'Confirma tu suscripción al boletín — %s',
	'eee18abf' => 'Te has dado de baja del boletín. <strong>%s</strong> ya no recibirá boletines.',
	'efd27699' => 'Asunto',
	'f4d13508' => 'Aún no se ha enviado ninguna campaña.',
	'f6f03446' => 'Redactar un boletín',
	'f705dfc0' => 'Has solicitado suscribirte al boletín de <strong>%s</strong> con el correo <code>%s</code>.',
	'056af2ff' => 'Suscripción al boletín (doble opt-in) y envío de campañas.',
];
