<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (fr)
 */

return [
	'02f6b476' => 'Auteur',
	'037b7df2' => 'Aucun abonné.',
	'06fdbe1b' => 'Inscription confirmée ! Tu recevras les prochaines newsletters à <strong>%s</strong>.',
	'0aac9844' => 'Date',
	'0e064b5e' => 'Inscris-toi à la newsletter pour recevoir les actualités du site directement par email.',
	'14adda10' => 'Gérer abonnés',
	'16679980' => 'Pour confirmer ton inscription, clique sur le bouton ci-dessous :',
	'180c83ba' => 'Gère ta liste d\'abonnés et l\'envoi de campagnes. Le double opt-in est activé : les abonnés doivent confirmer via email avant d\'apparaître dans tes campagnes.',
	'1f0aec47' => 'Confirmer mon inscription',
	'2008a6f2' => 'Date inscription',
	'26535370' => 'Email',
	'31d88618' => 'Newsletter',
	'361b67f5' => 'Supprimer cet abonné ?',
	'3d3a71d9' => 'Email de confirmation envoyé à %s',
	'526e2d7b' => 'Cet email a déjà demandé l\'inscription. Vérifie ta boîte mail pour le lien de confirmation.',
	'56dca9ce' => 'Confirmation newsletter',
	'573ff81d' => 'Confirmé',
	'6105648e' => 'Composer',
	'6335835b' => 'Contenu (HTML)',
	'65bdf3ec' => 'Campagne envoyée à %d abonné(s).',
	'7fd41a45' => 'En attente',
	'85d740f8' => 'Cet email est déjà inscrit à la newsletter.',
	'8afe3630' => 'Abonnés confirmés',
	'8cb61d4a' => 'Bonjour,',
	'8d9ef7a4' => 'Supprimer',
	'9da30cd1' => 'Se désinscrire',
	'a1442451' => 'Historique campagnes',
	'a29c9965' => 'Nouvelle campagne',
	'a2e2d63c' => 'Historique',
	'a3134b9d' => 'Si tu n\'es pas à l\'origine de cette demande, ignore ce mail.',
	'b5ad91ec' => 'double opt-in non confirmé',
	'b68fdf69' => 'Destinataires',
	'b6d15296' => 'S\'inscrire',
	'bca59417' => 'HTML autorisé. Un lien de désinscription sera ajouté automatiquement.',
	'bd45bb7a' => 'Abonnés',
	'c06ad4f3' => 'Email déjà confirmé. Tu es bien inscrit à la newsletter.',
	'c1d8f9a3' => 'Adresse email',
	'c3792c02' => 'Abonnés newsletter',
	'c55f374f' => 'Abonné supprimé.',
	'c6e0ee98' => 'Historique des campagnes',
	'caf5c873' => 'Actions',
	'cd539fe1' => 'Tu reçois ce mail car tu es inscrit à la newsletter de %s.',
	'cea5b394' => 'Envoyer à %d abonné(s) confirmé(s)',
	'cec4ef4d' => 'Campagnes envoyées',
	'd38f95dd' => 'Sujet',
	'dbbd5005' => 'Désinscription',
	'e2c8f589' => 'Statut',
	'ea284657' => 'Envoyer campagnes',
	'edfc132e' => 'Confirme ton inscription à la newsletter — %s',
	'eee18abf' => 'Tu as bien été désinscrit de la newsletter. <strong>%s</strong> ne recevra plus de newsletters.',
	'efd27699' => 'Sujet',
	'f4d13508' => 'Aucune campagne envoyée pour le moment.',
	'f6f03446' => 'Composer une newsletter',
	'f705dfc0' => 'Tu as demandé l\'inscription à la newsletter de <strong>%s</strong> avec l\'email <code>%s</code>.'
];
