<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (it)
 */

return [
	'02f6b476' => 'Autore',
	'037b7df2' => 'Nessun iscritto.',
	'06fdbe1b' => 'Iscrizione confermata! Riceverai le prossime newsletter all\'indirizzo <strong>%s</strong>.',
	'0aac9844' => 'Data',
	'0e064b5e' => 'Iscriviti alla newsletter per ricevere le novità del sito direttamente via email.',
	'14adda10' => 'Gestisci iscritti',
	'16679980' => 'Per confermare la tua iscrizione, clicca sul pulsante qui sotto:',
	'180c83ba' => 'Gestisci la tua lista di iscritti e l\'invio delle campagne. Il double opt-in è attivato: gli iscritti devono confermare via email prima di apparire nelle tue campagne.',
	'1f0aec47' => 'Conferma la mia iscrizione',
	'2008a6f2' => 'Data iscrizione',
	'26535370' => 'Email',
	'31d88618' => 'Newsletter',
	'361b67f5' => 'Eliminare questo iscritto?',
	'3d3a71d9' => 'Email di conferma inviata a %s',
	'526e2d7b' => 'Questa email ha già richiesto l\'iscrizione. Controlla la tua casella per il link di conferma.',
	'56dca9ce' => 'Conferma newsletter',
	'573ff81d' => 'Confermato',
	'6105648e' => 'Componi',
	'6335835b' => 'Contenuto (HTML)',
	'65bdf3ec' => 'Campagna inviata a %d iscritti.',
	'7fd41a45' => 'In attesa',
	'85d740f8' => 'Questa email è già iscritta alla newsletter.',
	'8afe3630' => 'Iscritti confermati',
	'8cb61d4a' => 'Ciao,',
	'8d9ef7a4' => 'Elimina',
	'9da30cd1' => 'Disiscriviti',
	'a1442451' => 'Cronologia campagne',
	'a29c9965' => 'Nuova campagna',
	'a2e2d63c' => 'Cronologia',
	'a3134b9d' => 'Se non sei stato tu a inviare questa richiesta, ignora questa email.',
	'b5ad91ec' => 'double opt-in non confermato',
	'b68fdf69' => 'Destinatari',
	'b6d15296' => 'Iscriviti',
	'bca59417' => 'HTML consentito. Verrà aggiunto automaticamente un link di disiscrizione.',
	'bd45bb7a' => 'Iscritti',
	'c06ad4f3' => 'Email già confermata. Sei iscritto alla newsletter.',
	'c1d8f9a3' => 'Indirizzo email',
	'c3792c02' => 'Iscritti newsletter',
	'c55f374f' => 'Iscritto eliminato.',
	'c6e0ee98' => 'Cronologia campagne',
	'caf5c873' => 'Azioni',
	'cd539fe1' => 'Ricevi questa email perché sei iscritto alla newsletter di %s.',
	'cea5b394' => 'Invia a %d iscritti confermati',
	'cec4ef4d' => 'Campagne inviate',
	'd38f95dd' => 'Oggetto',
	'dbbd5005' => 'Annullamento iscrizione',
	'e2c8f589' => 'Stato',
	'ea284657' => 'Invia campagne',
	'edfc132e' => 'Conferma la tua iscrizione alla newsletter — %s',
	'eee18abf' => 'Sei stato disiscritto dalla newsletter. <strong>%s</strong> non riceverà più newsletter.',
	'efd27699' => 'Oggetto',
	'f4d13508' => 'Nessuna campagna inviata per ora.',
	'f6f03446' => 'Componi una newsletter',
	'f705dfc0' => 'Hai richiesto l\'iscrizione alla newsletter di <strong>%s</strong> con l\'email <code>%s</code>.',
	'056af2ff' => 'Iscrizione alla newsletter (double opt-in) e invio di campagne.',
];
