<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — module newsletter (pt)
 */

return [
	'02f6b476' => 'Autor',
	'037b7df2' => 'Sem subscritores.',
	'06fdbe1b' => 'Subscrição confirmada! Receberás as próximas newsletters em <strong>%s</strong>.',
	'0aac9844' => 'Data',
	'0e064b5e' => 'Subscreve a newsletter para receberes as novidades do site diretamente por e-mail.',
	'14adda10' => 'Gerir subscritores',
	'16679980' => 'Para confirmar a tua subscrição, clica no botão abaixo:',
	'180c83ba' => 'Gere a tua lista de subscritores e o envio de campanhas. O duplo opt-in está ativo: os subscritores devem confirmar por e-mail antes de aparecerem nas tuas campanhas.',
	'1f0aec47' => 'Confirmar a minha subscrição',
	'2008a6f2' => 'Data da subscrição',
	'26535370' => 'E-mail',
	'31d88618' => 'Newsletter',
	'361b67f5' => 'Eliminar este subscritor?',
	'3d3a71d9' => 'E-mail de confirmação enviado para %s',
	'526e2d7b' => 'Este e-mail já pediu a subscrição. Verifica a caixa de entrada para o link de confirmação.',
	'56dca9ce' => 'Confirmação da newsletter',
	'573ff81d' => 'Confirmado',
	'6105648e' => 'Compor',
	'6335835b' => 'Conteúdo (HTML)',
	'65bdf3ec' => 'Campanha enviada a %d subscritor(es).',
	'7fd41a45' => 'Pendente',
	'85d740f8' => 'Este e-mail já está subscrito à newsletter.',
	'8afe3630' => 'Subscritores confirmados',
	'8cb61d4a' => 'Olá,',
	'8d9ef7a4' => 'Eliminar',
	'9da30cd1' => 'Cancelar subscrição',
	'a1442451' => 'Histórico de campanhas',
	'a29c9965' => 'Nova campanha',
	'a2e2d63c' => 'Histórico',
	'a3134b9d' => 'Se não foste tu a originar este pedido, ignora este e-mail.',
	'b5ad91ec' => 'double opt-in não confirmado',
	'b68fdf69' => 'Destinatários',
	'b6d15296' => 'Subscrever',
	'bca59417' => 'HTML permitido. Será adicionado automaticamente um link para cancelar a subscrição.',
	'bd45bb7a' => 'Subscritores',
	'c06ad4f3' => 'E-mail já confirmado. Estás subscrito à newsletter.',
	'c1d8f9a3' => 'Endereço de e-mail',
	'c3792c02' => 'Subscritores da newsletter',
	'c55f374f' => 'Subscritor eliminado.',
	'c6e0ee98' => 'Histórico das campanhas',
	'caf5c873' => 'Ações',
	'cd539fe1' => 'Recebes este e-mail porque estás subscrito à newsletter de %s.',
	'cea5b394' => 'Enviar para %d subscritor(es) confirmado(s)',
	'cec4ef4d' => 'Campanhas enviadas',
	'd38f95dd' => 'Assunto',
	'dbbd5005' => 'Cancelar subscrição',
	'e2c8f589' => 'Estado',
	'ea284657' => 'Enviar campanhas',
	'edfc132e' => 'Confirma a tua subscrição da newsletter — %s',
	'eee18abf' => 'Foste removido da newsletter. <strong>%s</strong> não receberá mais newsletters.',
	'efd27699' => 'Assunto',
	'f4d13508' => 'Nenhuma campanha enviada ainda.',
	'f6f03446' => 'Compor uma newsletter',
	'f705dfc0' => 'Pediste a subscrição da newsletter de <strong>%s</strong> com o e-mail <code>%s</code>.',
	'056af2ff' => 'Inscrição na newsletter (double opt-in) e envio de campanhas.',
];
