-- Les comptes inactifs s'effacent (décision du 2026-10-09, entrée d04 du tableau ; ligne 0.45 du reste-à-faire).
--
-- La CNIL attend une durée de conservation pour un compte qui ne sert plus : trois ans sans visite par défaut, réglable
-- dans Paramètres (nf_comptes_inactifs_ans, 0 : jamais). Un courriel prévient le membre un mois avant ; une visite annule
-- tout. nf_user_inactivite garde la date de la prévenance (User::menage_des_comptes_inactifs()).

CREATE TABLE IF NOT EXISTS `nf_user_inactivite` (
  `user_id` int(11) unsigned NOT NULL,
  `prevenu_le` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_inactivite_user` FOREIGN KEY (`user_id`) REFERENCES `nf_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `nf_settings` (`name`, `site`, `lang`, `value`, `type`) VALUES ('nf_comptes_inactifs_ans', '', '', '3', 'int');

INSERT IGNORE INTO `nf_email_templates` (`key`, `title`, `description`, `placeholders`, `module`, `enabled`) VALUES ('user.inactivite', 'Compte inactif bientôt effacé', 'Envoyé un mois avant d\'effacer un compte resté sans visite (Paramètres : comptes inactifs).', '[\"{{username}}\",\"{{site_name}}\",\"{{date}}\",\"{{connexion_url}}\"]', 'user', 1);
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'de', 'Dein Konto auf {{site_name}} wird am {{date}} gelöscht', '<p>Hallo <strong>{{username}}</strong>,</p><p>du hast dich lange nicht mehr auf <strong>{{site_name}}</strong> angemeldet. Konten ohne Besuch werden gelöscht, damit deine Daten nicht grundlos aufbewahrt werden: deines am <strong>{{date}}</strong>.</p><p>Um es zu behalten, melde dich einfach bis dahin an:</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Anmelden</a></p><p>Wenn du es nicht mehr möchtest, musst du nichts tun.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'en', 'Your account on {{site_name}} will be deleted on {{date}}', '<p>Hello <strong>{{username}}</strong>,</p><p>You have not signed in to <strong>{{site_name}}</strong> for a long time. Accounts left without a visit are deleted, so that your data is not kept for no reason: yours will be on <strong>{{date}}</strong>.</p><p>To keep it, just sign in before then:</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Sign in</a></p><p>If you no longer want it, you do not need to do anything.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'es', 'Tu cuenta en {{site_name}} se eliminará el {{date}}', '<p>Hola <strong>{{username}}</strong>,</p><p>Hace mucho que no inicias sesión en <strong>{{site_name}}</strong>. Las cuentas sin visitas se eliminan para no conservar tus datos sin motivo: la tuya lo será el <strong>{{date}}</strong>.</p><p>Para conservarla, basta con que inicies sesión antes de esa fecha:</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Iniciar sesión</a></p><p>Si ya no la quieres, no tienes que hacer nada.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'fr', 'Ton compte sur {{site_name}} sera effacé le {{date}}', '<p>Bonjour <strong>{{username}}</strong>,</p><p>Tu ne t\'es pas connecté à <strong>{{site_name}}</strong> depuis longtemps. Les comptes restés sans visite sont effacés, pour ne pas garder tes données sans raison : le tien le sera le <strong>{{date}}</strong>.</p><p>Pour le garder, il suffit de te connecter d\'ici là :</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Me connecter</a></p><p>Si tu n\'en veux plus, tu n\'as rien à faire.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'it', 'Il tuo account su {{site_name}} sarà eliminato il {{date}}', '<p>Ciao <strong>{{username}}</strong>,</p><p>non accedi a <strong>{{site_name}}</strong> da molto tempo. Gli account senza visite vengono eliminati per non conservare i tuoi dati senza motivo: il tuo lo sarà il <strong>{{date}}</strong>.</p><p>Per conservarlo, basta accedere entro quella data:</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Accedi</a></p><p>Se non lo vuoi più, non devi fare nulla.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'pt', 'A tua conta em {{site_name}} será eliminada a {{date}}', '<p>Olá <strong>{{username}}</strong>,</p><p>Não inicias sessão em <strong>{{site_name}}</strong> há muito tempo. As contas sem visitas são eliminadas para não guardar os teus dados sem motivo: a tua sê-lo-á a <strong>{{date}}</strong>.</p><p>Para a manteres, basta iniciares sessão até lá:</p><p><a href=\"{{connexion_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Iniciar sessão</a></p><p>Se já não a quiseres, não tens de fazer nada.</p>' FROM `nf_email_templates` WHERE `key` = 'user.inactivite';
