-- La nouvelle adresse e-mail d'un membre attend sa confirmation (2026-10-09, ligne 0.29 du tableau de bord).
--
-- Une adresse saisie dans « Mon compte » était prise telle quelle : une faute de frappe, et le membre ne recevait
-- plus rien. Elle attend maintenant ici le clic sur le lien envoyé à la nouvelle adresse (valable deux jours),
-- et l'ancienne adresse est prévenue de la demande. Une table à part : la table des jetons sert au mot de passe
-- oublié, et un jeton y efface les précédents.

CREATE TABLE IF NOT EXISTS `nf_user_email_change` (
  `user_id` int(11) unsigned NOT NULL,
  `email` varchar(100) NOT NULL,
  `token` char(32) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_token` (`token`),
  CONSTRAINT `fk_user_email_change_user` FOREIGN KEY (`user_id`) REFERENCES `nf_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `nf_email_templates` (`key`, `title`, `description`, `placeholders`, `module`, `enabled`) VALUES ('user.email_change', 'Confirmation de la nouvelle adresse', 'Envoyé à la nouvelle adresse e-mail d\'un membre, avec le lien qui la confirme.', '[\"{{username}}\",\"{{site_name}}\",\"{{email}}\",\"{{confirmation_url}}\"]', 'user', 1);
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'de', 'Bestätige deine neue Adresse auf {{site_name}}', '<p>Hallo <strong>{{username}}</strong>,</p><p>Du hast beantragt, die E-Mail-Adresse deines Kontos auf <strong>{{site_name}}</strong> durch diese zu ersetzen: <strong>{{email}}</strong>. Um sie zu bestätigen, klicke auf den Link unten; er bleibt zwei Tage gültig:</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Diese Adresse bestätigen</a></p><p>Falls der Button nicht funktioniert, kopiere diese URL in deinen Browser:<br><code>{{confirmation_url}}</code></p><p>Wenn du diese Anfrage nicht gestellt hast, ignoriere diese E-Mail einfach: Deine Adresse ändert sich nicht.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'en', 'Confirm your new address on {{site_name}}', '<p>Hello <strong>{{username}}</strong>,</p><p>You asked to replace the email address of your account on <strong>{{site_name}}</strong> with this one: <strong>{{email}}</strong>. To confirm it, click the link below; it stays valid for two days:</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Confirm this address</a></p><p>If the button does not work, copy and paste this URL into your browser:<br><code>{{confirmation_url}}</code></p><p>If you did not make this request, simply ignore this email: your address will not change.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'es', 'Confirma tu nueva dirección en {{site_name}}', '<p>Hola <strong>{{username}}</strong>,</p><p>Has pedido sustituir la dirección de correo de tu cuenta en <strong>{{site_name}}</strong> por esta: <strong>{{email}}</strong>. Para confirmarla, haz clic en el enlace de abajo; sigue siendo válido durante dos días:</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Confirmar esta dirección</a></p><p>Si el botón no funciona, copia y pega esta URL en tu navegador:<br><code>{{confirmation_url}}</code></p><p>Si no has hecho esta solicitud, simplemente ignora este correo: tu dirección no cambiará.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'fr', 'Confirme ta nouvelle adresse sur {{site_name}}', '<p>Bonjour <strong>{{username}}</strong>,</p><p>Tu as demandé à remplacer l\'adresse e-mail de ton compte sur <strong>{{site_name}}</strong> par celle-ci : <strong>{{email}}</strong>. Pour la confirmer, clique sur le lien ci-dessous ; il reste valable deux jours :</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Confirmer cette adresse</a></p><p>Si le bouton ne fonctionne pas, copie-colle cette URL dans ton navigateur :<br><code>{{confirmation_url}}</code></p><p>Si tu n\'es pas à l\'origine de cette demande, ignore simplement cet e-mail : ton adresse ne changera pas.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'it', 'Conferma il tuo nuovo indirizzo su {{site_name}}', '<p>Ciao <strong>{{username}}</strong>,</p><p>Hai chiesto di sostituire l\'indirizzo e-mail del tuo account su <strong>{{site_name}}</strong> con questo: <strong>{{email}}</strong>. Per confermarlo, fai clic sul link qui sotto; resta valido per due giorni:</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Conferma questo indirizzo</a></p><p>Se il pulsante non funziona, copia e incolla questo URL nel browser:<br><code>{{confirmation_url}}</code></p><p>Se non hai fatto tu questa richiesta, ignora semplicemente questa e-mail: il tuo indirizzo non cambierà.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'pt', 'Confirma o teu novo endereço em {{site_name}}', '<p>Olá <strong>{{username}}</strong>,</p><p>Pediste para substituir o endereço de e-mail da tua conta em <strong>{{site_name}}</strong> por este: <strong>{{email}}</strong>. Para o confirmar, clica na ligação abaixo; continua válida durante dois dias:</p><p><a href=\"{{confirmation_url}}\" style=\"display:inline-block;padding:10px 20px;background:#027a66;color:#fff;text-decoration:none;border-radius:4px;\">Confirmar este endereço</a></p><p>Se o botão não funcionar, copia e cola este URL no teu navegador:<br><code>{{confirmation_url}}</code></p><p>Se não fizeste este pedido, ignora simplesmente este e-mail: o teu endereço não vai mudar.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change';

INSERT IGNORE INTO `nf_email_templates` (`key`, `title`, `description`, `placeholders`, `module`, `enabled`) VALUES ('user.email_change_notice', 'Changement d\'adresse demandé', 'Envoyé à l\'ancienne adresse d\'un membre quand il en demande une nouvelle.', '[\"{{username}}\",\"{{site_name}}\",\"{{email}}\"]', 'user', 1);
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'de', 'Adressänderung beantragt auf {{site_name}}', '<p>Hallo <strong>{{username}}</strong>,</p><p>Soeben wurde beantragt, die E-Mail-Adresse deines Kontos auf <strong>{{site_name}}</strong> zu ersetzen durch: <strong>{{email}}</strong>. Die Änderung gilt erst, wenn sie von dieser neuen Adresse aus bestätigt wurde.</p><p>Wenn du diese Anfrage nicht gestellt hast, ändere sofort dein Passwort und informiere das Team der Website.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'en', 'Address change requested on {{site_name}}', '<p>Hello <strong>{{username}}</strong>,</p><p>Someone just asked to replace the email address of your account on <strong>{{site_name}}</strong> with: <strong>{{email}}</strong>. It will only take effect once confirmed from that new address.</p><p>If you did not make this request, change your password right away and let the site team know.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'es', 'Cambio de dirección solicitado en {{site_name}}', '<p>Hola <strong>{{username}}</strong>,</p><p>Se acaba de pedir sustituir la dirección de correo de tu cuenta en <strong>{{site_name}}</strong> por: <strong>{{email}}</strong>. Solo surtirá efecto una vez confirmada desde esa nueva dirección.</p><p>Si no has hecho esta solicitud, cambia tu contraseña ahora mismo y avisa al equipo del sitio.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'fr', 'Changement d\'adresse demandé sur {{site_name}}', '<p>Bonjour <strong>{{username}}</strong>,</p><p>Le remplacement de l\'adresse e-mail de ton compte sur <strong>{{site_name}}</strong> vient d\'être demandé, vers : <strong>{{email}}</strong>. Il ne prendra effet qu\'une fois confirmé depuis cette nouvelle adresse.</p><p>Si tu n\'es pas à l\'origine de cette demande, change ton mot de passe dès maintenant et préviens l\'équipe du site.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'it', 'Cambio di indirizzo richiesto su {{site_name}}', '<p>Ciao <strong>{{username}}</strong>,</p><p>È appena stato chiesto di sostituire l\'indirizzo e-mail del tuo account su <strong>{{site_name}}</strong> con: <strong>{{email}}</strong>. Avrà effetto solo dopo la conferma da questo nuovo indirizzo.</p><p>Se non hai fatto tu questa richiesta, cambia subito la password e avvisa lo staff del sito.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
INSERT IGNORE INTO `nf_email_template_translations` (`template_id`, `lang`, `subject`, `body`) SELECT `template_id`, 'pt', 'Pedido de mudança de endereço em {{site_name}}', '<p>Olá <strong>{{username}}</strong>,</p><p>Acaba de ser pedido substituir o endereço de e-mail da tua conta em <strong>{{site_name}}</strong> por: <strong>{{email}}</strong>. Só terá efeito depois de confirmado a partir desse novo endereço.</p><p>Se não fizeste este pedido, muda já a tua palavra-passe e avisa a equipa do site.</p>' FROM `nf_email_templates` WHERE `key` = 'user.email_change_notice';
