<?php
/**
 * https://translate.neofr.ag
 */

return [
	'12415cd6' => 'HTML/CSS rendering integrated with the site theme (recommended)',
	'201ec864' => 'In your Discord server, click <strong>Server Settings</strong>',
	'409bfe55' => 'Differences between modes:',
	'54a31313' => 'Copy the server ID (Discord developer mode required: <em>User Settings → Advanced → Developer Mode</em>)',
	'6a97e63a' => 'Numeric Snowflake ID of the server (right-click on server name in Discord → "Copy Server ID"). Dev mode required.',
	'6cb57f33' => 'Theme (iframe)',
	'd743b52b' => 'Optional. Otherwise the link is fetched automatically from Discord.',
	'8f44c74a' => 'This Discord server\'s widget is not enabled: <strong>Server Settings → Widget → Enable Server Widget</strong>.',
	'fee4ebb0' => 'Discord server ID not found. Enable <strong>Developer Mode</strong> (Settings → Advanced), then right-click the <strong>server</strong> → "Copy Server ID" (not to be confused with a channel ID or an invite code).',
	'ae074439' => 'Discord server unreachable. If your hosting blocks outbound requests, switch the widget to <strong>iframe</strong> mode in its settings.',
	'9a81093c' => 'Discord-side error (%s). Try again in a few minutes.',
	'e16d555c' => 'Native',
	'fdd16ad9' => 'Native (integrated to the theme)',
	'816f205c' => 'Discord',
	'4b9e75a1' => 'Please configure the Discord server ID in the admin panel.',
	'5b5583b2' => 'Discord server',
	'6bd10de9' => 'Shows online members, voice channels and an invite link to your Discord server.',
	'1f88c31b' => 'Options',
	'79a32b9f' => 'Help',
	'f17b1287' => 'Server ID',
	'ea59365b' => 'Display mode',
	'1d70079f' => 'Official Discord iframe',
	'f66ed182' => 'Invite link',
	'82748555' => 'Dark',
	'eba0fcd6' => 'Light',
	'23bd043a' => 'Height (iframe, px)',
	'0dda30a2' => 'How to enable the Discord widget?',
	'bb31a60e' => 'Go to <strong>Widget</strong>',
	'662aacc8' => 'Enable <strong>Enable server widget</strong>',
	'ea4f31d7' => 'Iframe',
	'c0e8f575' => 'official Discord widget, heavier, fixed look',
	'2547c34e' => '%d others',
	'a12b1086' => 'Voice channels',
	'f930d5d6' => 'Join the server',
	'5b00c662' => 'members online',
	'2aa68b91' => 'member online',
];
