<?php
/**
 * https://translate.neofr.ag
 */

return [
	'12415cd6' => 'Renderizado HTML/CSS integrado con el tema del sitio (recomendado)',
	'201ec864' => 'En tu servidor de Discord, haz clic en <strong>Configuración del servidor</strong>',
	'409bfe55' => 'Diferencias entre los modos:',
	'54a31313' => 'Copia el ID del servidor (modo desarrollador de Discord requerido: <em>Ajustes de usuario → Avanzado → Modo desarrollador</em>)',
	'6a97e63a' => 'Snowflake ID numérico del servidor (clic derecho en el nombre del servidor en Discord → "Copiar ID del servidor"). Modo dev requerido.',
	'6cb57f33' => 'Tema (iframe)',
	'd743b52b' => 'Opcional. De lo contrario, el enlace se obtiene automáticamente de Discord.',
	'8f44c74a' => 'El widget de este servidor de Discord no está activado: <strong>Configuración del servidor → Widget → Activar widget del servidor</strong>.',
	'fee4ebb0' => 'ID de servidor de Discord no encontrado. Activa el <strong>Modo desarrollador</strong> (Ajustes → Avanzado), luego clic derecho en el <strong>servidor</strong> → "Copiar ID del servidor" (no confundir con un ID de canal o un código de invitación).',
	'ae074439' => 'Servidor de Discord inalcanzable. Si tu alojamiento bloquea las peticiones salientes, cambia el widget al modo <strong>iframe</strong> en sus ajustes.',
	'9a81093c' => 'Error del lado de Discord (%s). Inténtalo de nuevo en unos minutos.',
	'e16d555c' => 'Nativo',
	'fdd16ad9' => 'Nativo (integrado en el tema)',
	'816f205c' => 'Discord',
	'4b9e75a1' => 'Configura el ID del servidor Discord en el panel de administración.',
	'5b5583b2' => 'Servidor Discord',
	'6bd10de9' => 'Muestra los miembros en línea, los canales de voz y un enlace de invitación a tu servidor Discord.',
	'1f88c31b' => 'Opciones',
	'79a32b9f' => 'Ayuda',
	'f17b1287' => 'ID del servidor',
	'ea59365b' => 'Modo de visualización',
	'1d70079f' => 'Iframe oficial de Discord',
	'f66ed182' => 'Enlace de invitación',
	'82748555' => 'Oscuro',
	'eba0fcd6' => 'Claro',
	'23bd043a' => 'Altura (iframe, px)',
	'0dda30a2' => '¿Cómo activar el widget Discord?',
	'bb31a60e' => 'Ve a <strong>Widget</strong>',
	'662aacc8' => 'Activa <strong>Activar el widget del servidor</strong>',
	'ea4f31d7' => 'Iframe',
	'c0e8f575' => 'widget oficial de Discord, más pesado, aspecto fijo',
	'2547c34e' => '%d más',
	'a12b1086' => 'Canales de voz',
	'f930d5d6' => 'Unirse al servidor',
	'5b00c662' => 'miembros en línea',
	'2aa68b91' => 'miembro en línea',
];
