<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Themes',
	'2b6a01e8' => 'Bitte laden Sie ein Theme als .zip herunter',
	'2b9cde0b' => 'Authentifikatoren',
	'3d4e511c' => 'Konfiguration von <b>%s</b> aktualisiert',
	'45a26340' => '.zip-Theme herunterladen (max. %d MB)',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Möchten Sie das Theme <b>%s</b> wirklich neu installieren?<br />Alle Widget-Layouts und Konfigurationen gehen verloren.',
	'717adbf5' => 'Theme löschen',
	'8c65c71b' => '<b>%s</b> aktiviert',
	'8d8bc95c' => '<b>%s</b> deaktiviert',
	'aa8e1f61' => 'Diese Version ist bereits installiert',
	'b0d653e1' => 'Inaktiv',
	'b97fd3c7' => 'Anpassen',
	'bde466c1' => 'Alle',
	'c9340a06' => 'Aktiv',
	'caf5c873' => 'Aktionen',
	'ccb3cbb6' => 'Inaktiv',
	'd5a02f7c' => 'Theme %s auf Standardwerte zurückgesetzt',
	'dbde31be' => 'Liste der installierten Themes',
	'dc275fe4' => 'Filter',
	'de200fc5' => 'Sprachen',
	'e10a7a4b' => 'Module',
	'e6277648' => 'Eine neuere Version dieses Themes ist bereits installiert',
	'f2a45e34' => 'Aktiv',
	'fa716ede' => 'Theme wird angepasst',
	'43a89cf7' => 'Standardeinstellungen wiederherstellen',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Das Theme <b>%s</b> endgültig löschen?<br />Seine Layouts, Konfiguration und Dateien werden entfernt. Diese Aktion ist unwiderruflich.',
	'bc34fea3' => 'Theme %s gelöscht',
	'18220db0' => 'Archiv abgelehnt: Es enthält einen unsicheren Pfad.',
	'ed086de3' => 'Marketplace derzeit nicht erreichbar, versuche es später erneut.',
	'bded9c78' => 'Alle Marketplace-Addons sind bereits installiert.',
	'96bbd960' => '%d Addon(s) im Marketplace verfügbar. Bei der Installation heruntergeladen und verifiziert (SHA-256).',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> nicht installiert: %s',
	'12996e78' => '<b>%s</b> aus dem Marketplace installiert',
	'4283c42c' => 'Marketplace nicht erreichbar: Updates können nicht geprüft werden.',
	'10b182db' => '<b>NeoFrag %s</b> ist verfügbar (du nutzt %s). Lade die Release herunter und ersetze die Dateien — außer <code>config/</code>, <code>upload/</code>, <code>backups/</code> — und besuche dann die Website (Migrationen werden angewendet).',
	'd617b951' => 'Alle deine Addons sind aktuell.',
	'd57a273d' => '%d Update(s) verfügbar. Vor der Anwendung heruntergeladen und verifiziert (SHA-256).',
	'4834bc18' => 'Widget <b>%s</b> nicht aktualisiert: %s',
	'a80d96ac' => '<b>%s</b> auf Version %s aktualisiert',
	'14fc77c5' => 'Kein neues Addon auf der Festplatte erkannt.',
	'8979133d' => '%d Addon(s) auf der Festplatte erkannt. Wähle die zu installierenden aus.',
	'a8ac13ba' => '<b>%s</b> installiert',
	'3fa04ac8' => 'Kein Addon installiert.',
	'd97a432e' => '<b>%s</b> benötigt: %s. Installiere sie zuerst.',
	'77a7bf71' => 'Informationen',
	'1f86fdde' => 'Themes & Addons',
	'ffcc0375' => 'Verwaltung der installierten Module, Widgets, Themes, Sprachen und Authentifikatoren.',
	'27eee9ef' => 'Authentifikator',
	'eb6693d4' => 'Deaktivieren',
	'b2b8bdcd' => 'Reihenfolge',
	'635277da' => 'Registrieren Sie Ihre Website über',
	'c3c7303b' => 'Entwicklung',
	'9cb0b230' => 'Produktion',
	'94fb70b8' => 'Sprache',
	'aa957e20' => 'Spracheinstellungen',
	'd1871ac3' => 'Theme',
	'a730190a' => 'Theme löschen',
	'82551be6' => 'Widget',
	'7810a681' => 'Festplatte durchsuchen',
	'fe033a6b' => 'Updates',
	'e0a855b1' => 'Marketplace',
	'0c242628' => 'Modul',
	'85f91ed0' => 'Widget',
	'd62b1ff5' => 'Theme',
	'8e49d0be' => 'Das %s %s ist bereits in Version %s installiert',
	'86a093ba' => 'Das %s %s ist bereits in einer höheren Version installiert',
	'799af6ae' => 'Das %s %s wurde installiert',
	'c4f5b0f2' => 'Das %s %s wurde aktualisiert',
	'73667835' => 'Das %s %s konnte nicht installiert werden',
	'5c4047f8' => 'Das %s %s konnte nicht aktualisiert werden',
	'bbf2634a' => 'Das %s %s erfordert NeoFrag in Version %s, bitte aktualisieren Sie Ihre Website',
	'afb536e2' => 'Die Komponente kann nicht installiert werden, bitte prüfen Sie, ob die Versionsnummern vorhanden sind',
	'9f2be5d5' => 'Die Komponente kann nicht installiert werden, bitte prüfen Sie ihren Inhalt',
	'8d8a9bda' => '%d KB',
	'9ed642e7' => 'Aktualisieren',
	'30d19292' => 'Authentifikator',
	'9fa5be42' => 'Auswahl installieren',
	'2cecf817' => 'Typ',
	'430d09b2' => 'Erweiterung suchen',
	'e2c8f589' => 'Status',
	'8088964a' => 'Anzeige',
	'3d3305f0' => 'Liste',
	'd3fe1369' => 'Programm',
	'45002a02' => 'Keine Erweiterung entspricht.',
	'79e64a05' => '<b>NeoFrag %s</b> ist verfügbar (du verwendest %s): <a href="%s">Monitoring</a> aktualisiert es mit einem Klick und legt vorher eine Sicherung an.',
	'62ad9179' => '%d Marketplace-Addon(s) benötigen eine neuere Version von NeoFrag: Aktualisiere zuerst deine Website.',
];
