<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Themes',
	'2b6a01e8' => 'Bitte laden Sie ein Theme als .zip herunter',
	'2b9cde0b' => 'Authentifikatoren',
	'3d4e511c' => 'Konfiguration von <b>%s</b> aktualisiert',
	'45a26340' => '.zip-Theme herunterladen (max. %d MB)',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Möchten Sie das Theme <b>%s</b> wirklich neu installieren?<br />Alle Widget-Layouts und Konfigurationen gehen verloren.',
	'717adbf5' => 'Theme löschen',
	'8c65c71b' => '<b>%s</b> aktiviert',
	'8d8bc95c' => '<b>%s</b> deaktiviert',
	'aa8e1f61' => 'Diese Version ist bereits installiert',
	'b0d653e1' => 'Inaktiv',
	'b97fd3c7' => 'Anpassen',
	'bde466c1' => 'Alle',
	'c9340a06' => 'Aktiv',
	'caf5c873' => 'Aktionen',
	'ccb3cbb6' => 'Inaktiv',
	'd5a02f7c' => 'Theme %s auf Standardwerte zurückgesetzt',
	'dbde31be' => 'Liste der installierten Themes',
	'dc275fe4' => 'Filter',
	'de200fc5' => 'Sprachen',
	'e10a7a4b' => 'Module',
	'e6277648' => 'Eine neuere Version dieses Themes ist bereits installiert',
	'f2a45e34' => 'Aktiv',
	'fa716ede' => 'Theme wird angepasst',
	'43a89cf7' => 'Standardeinstellungen wiederherstellen',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Das Theme <b>%s</b> endgültig löschen?<br />Seine Layouts, Konfiguration und Dateien werden entfernt. Diese Aktion ist unwiderruflich.',
	'bc34fea3' => 'Theme %s gelöscht',
	'18220db0' => 'Archiv abgelehnt: Es enthält einen unsicheren Pfad.',
	'ed086de3' => 'Marketplace derzeit nicht erreichbar, versuche es später erneut.',
	'bded9c78' => 'Alle Marketplace-Addons sind bereits installiert.',
	'96bbd960' => '%d Addon(s) im Marketplace verfügbar. Bei der Installation heruntergeladen und verifiziert (SHA-256).',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> nicht installiert: %s',
	'12996e78' => '<b>%s</b> aus dem Marketplace installiert',
	'4283c42c' => 'Marketplace nicht erreichbar: Updates können nicht geprüft werden.',
	'10b182db' => '<b>NeoFrag %s</b> ist verfügbar (du nutzt %s). Lade die Release herunter und ersetze die Dateien — außer <code>config/</code>, <code>upload/</code>, <code>backups/</code> — und besuche dann die Website (Migrationen werden angewendet).',
	'd617b951' => 'Alle deine Addons sind aktuell.',
	'd57a273d' => '%d Update(s) verfügbar. Vor der Anwendung heruntergeladen und verifiziert (SHA-256).',
	'4834bc18' => 'Widget <b>%s</b> nicht aktualisiert: %s',
	'a80d96ac' => '<b>%s</b> auf Version %s aktualisiert',
	'14fc77c5' => 'Kein neues Addon auf der Festplatte erkannt.',
	'8979133d' => '%d Addon(s) auf der Festplatte erkannt. Wähle die zu installierenden aus.',
	'a8ac13ba' => '<b>%s</b> installiert',
	'3fa04ac8' => 'Kein Addon installiert.',
];
