<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Themes',
	'2b6a01e8' => 'Please download a .zip theme',
	'2b9cde0b' => 'Authenticators',
	'3d4e511c' => 'Configuration for <b>%s</b> updated',
	'45a26340' => 'Download a .zip (max. %dMB) theme',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Are you sure you want to reinstall the theme <b>%s</b>?<br />All widget layouts and configurations will be lost.',
	'717adbf5' => 'Delete theme',
	'8c65c71b' => '<b>%s</b> enabled',
	'8d8bc95c' => '<b>%s</b> disabled',
	'aa8e1f61' => 'This version is already installed',
	'b0d653e1' => 'Inactive',
	'b97fd3c7' => 'Customize',
	'bde466c1' => 'All',
	'c9340a06' => 'Active',
	'caf5c873' => 'Actions',
	'ccb3cbb6' => 'Inactive',
	'd5a02f7c' => 'Theme %s reinstalled to defaults',
	'dbde31be' => 'List of installed themes',
	'dc275fe4' => 'Filter',
	'de200fc5' => 'Languages',
	'e10a7a4b' => 'Modules',
	'e6277648' => 'A newer version of this theme is already installed',
	'f2a45e34' => 'Active',
	'fa716ede' => 'Customizing theme',
	'43a89cf7' => 'Reinstall to defaults',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Permanently delete the theme <b>%s</b>?<br />Its layouts, configuration and files will be removed. This action is irreversible.',
	'bc34fea3' => 'Theme %s deleted',
	'18220db0' => 'Archive rejected: it contains an unsafe path.',
	'ed086de3' => 'Marketplace unreachable for now, try again later.',
	'bded9c78' => 'All marketplace addons are already installed.',
	'96bbd960' => '%d addon(s) available on the marketplace. Downloaded and verified (SHA-256) on installation.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> not installed: %s',
	'12996e78' => '<b>%s</b> installed from the marketplace',
	'4283c42c' => 'Marketplace unreachable: cannot check for updates.',
	'10b182db' => '<b>NeoFrag %s</b> is available (you are using %s). Download the release and replace the files — except <code>config/</code>, <code>upload/</code>, <code>backups/</code> — then visit the site (migrations apply).',
	'd617b951' => 'All your addons are up to date.',
	'd57a273d' => '%d update(s) available. Downloaded and verified (SHA-256) before applying.',
	'4834bc18' => 'Widget <b>%s</b> not updated: %s',
	'a80d96ac' => '<b>%s</b> updated to version %s',
	'14fc77c5' => 'No new addon detected on disk.',
	'8979133d' => '%d addon(s) detected on disk. Select the ones to install.',
	'a8ac13ba' => '<b>%s</b> installed',
	'3fa04ac8' => 'No addon installed.',
];
