<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 * @author: FoxLey
 * @author: eResnova
 * Complété par NeoFrag Reborn (traductions synchronisées le 2026-05-03).
 */

return [
	'19b2db1b' => 'Themes',
	'2b6a01e8' => 'Please download a .zip theme',
	'2b9cde0b' => 'Authenticators',
	'3d4e511c' => 'Configuration for <b>%s</b> updated',
	'45a26340' => 'Download a .zip (max. %dMB) theme',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Are you sure you want to reinstall the theme <b>%s</b>?<br />All widget layouts and configurations will be lost.',
	'717adbf5' => 'Delete theme',
	'8c65c71b' => '<b>%s</b> enabled',
	'8d8bc95c' => '<b>%s</b> disabled',
	'aa8e1f61' => 'This version is already installed',
	'b0d653e1' => 'Inactive',
	'b97fd3c7' => 'Customize',
	'bde466c1' => 'All',
	'c9340a06' => 'Active',
	'caf5c873' => 'Actions',
	'ccb3cbb6' => 'Inactive',
	'd5a02f7c' => 'Theme %s reinstalled to defaults',
	'dbde31be' => 'List of installed themes',
	'dc275fe4' => 'Filter',
	'de200fc5' => 'Languages',
	'e10a7a4b' => 'Modules',
	'e6277648' => 'A newer version of this theme is already installed',
	'f2a45e34' => 'Active',
	'fa716ede' => 'Customizing theme',
	'43a89cf7' => 'Reinstall to defaults',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Permanently delete the theme <b>%s</b>?<br />Its layouts, configuration and files will be removed. This action is irreversible.',
	'bc34fea3' => 'Theme %s deleted',
	'18220db0' => 'Archive rejected: it contains an unsafe path.',
	'ed086de3' => 'Marketplace unreachable for now, try again later.',
	'bded9c78' => 'All marketplace addons are already installed.',
	'96bbd960' => '%d addon(s) available on the marketplace. Downloaded and verified (SHA-256) on installation.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> not installed: %s',
	'12996e78' => '<b>%s</b> installed from the marketplace',
	'4283c42c' => 'Marketplace unreachable: cannot check for updates.',
	'10b182db' => '<b>NeoFrag %s</b> is available (you are using %s). Download the release and replace the files — except <code>config/</code>, <code>upload/</code>, <code>backups/</code> — then visit the site (migrations apply).',
	'd617b951' => 'All your addons are up to date.',
	'd57a273d' => '%d update(s) available. Downloaded and verified (SHA-256) before applying.',
	'4834bc18' => 'Widget <b>%s</b> not updated: %s',
	'a80d96ac' => '<b>%s</b> updated to version %s',
	'14fc77c5' => 'No new addon detected on disk.',
	'8979133d' => '%d addon(s) detected on disk. Select the ones to install.',
	'a8ac13ba' => '<b>%s</b> installed',
	'3fa04ac8' => 'No addon installed.',
	'd97a432e' => '<b>%s</b> requires: %s. Install them first.',
	'77a7bf71' => 'Information',
	'1f86fdde' => 'Themes & Addons',
	'ffcc0375' => 'Management of installed modules, widgets, themes, languages and authenticators.',
	'27eee9ef' => 'Authenticator',
	'eb6693d4' => 'Disable',
	'b2b8bdcd' => 'Order',
	'635277da' => 'Register your site via',
	'c3c7303b' => 'Development',
	'9cb0b230' => 'Production',
	'94fb70b8' => 'Language',
	'aa957e20' => 'Language preferences',
	'd1871ac3' => 'Theme',
	'a730190a' => 'Delete theme',
	'82551be6' => 'Widget',
	'7810a681' => 'Scan the disk',
	'fe033a6b' => 'Updates',
	'e0a855b1' => 'Marketplace',
	'0c242628' => 'module',
	'85f91ed0' => 'widget',
	'd62b1ff5' => 'theme',
	'8e49d0be' => 'The %s %s is already installed in version %s',
	'86a093ba' => 'The %s %s is already installed with a higher version',
	'799af6ae' => 'The %s %s has been installed',
	'c4f5b0f2' => 'The %s %s has been updated',
	'73667835' => 'The %s %s could not be installed',
	'5c4047f8' => 'The %s %s could not be updated',
	'bbf2634a' => 'The %s %s requires NeoFrag version %s, please update your site',
	'afb536e2' => 'The component cannot be installed, please check that the version numbers are present',
	'9f2be5d5' => 'The component cannot be installed, please check its content',
	'8d8a9bda' => '%d KB',
	'9ed642e7' => 'Update',
	'30d19292' => 'authenticator',
	'9fa5be42' => 'Install selection',
	'2cecf817' => 'Type',
	'430d09b2' => 'Search for an extension',
	'e2c8f589' => 'Status',
	'8088964a' => 'Display',
	'3d3305f0' => 'List',
	'd3fe1369' => 'Grid',
	'45002a02' => 'No extension matches.',
	'79e64a05' => '<b>NeoFrag %s</b> is available (you are using %s): <a href="%s">Monitoring</a> updates it in one click, taking a backup before writing anything.',
	'62ad9179' => '%d marketplace addon(s) require a newer version of NeoFrag: update your site first.',
];
