<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Temas',
	'2b6a01e8' => 'Por favor descargue un tema en formato .zip',
	'2b9cde0b' => 'Autenticadores',
	'3d4e511c' => 'Configuración de <b>%s</b> actualizada',
	'45a26340' => 'Descargar un tema .zip (máx. %dMB)',
	'52e5dd5d' => 'Widgets',
	'53513eff' => '¿Está seguro de que desea reinstalar el tema <b>%s</b>?<br />Se perderán todos los diseños y configuraciones de widgets.',
	'717adbf5' => 'Eliminar tema',
	'8c65c71b' => '<b>%s</b> activado',
	'8d8bc95c' => '<b>%s</b> desactivado',
	'aa8e1f61' => 'Esta versión ya está instalada',
	'b0d653e1' => 'Inactivo',
	'b97fd3c7' => 'Personalizar',
	'bde466c1' => 'Todos',
	'c9340a06' => 'Activo',
	'caf5c873' => 'Acciones',
	'ccb3cbb6' => 'Inactivos',
	'd5a02f7c' => 'Tema %s reinstalado a los valores predeterminados',
	'dbde31be' => 'Lista de temas instalados',
	'dc275fe4' => 'Filtrar',
	'de200fc5' => 'Idiomas',
	'e10a7a4b' => 'Módulos',
	'e6277648' => 'Ya está instalada una versión más reciente de este tema',
	'f2a45e34' => 'Activos',
	'fa716ede' => 'Personalizando tema',
	'43a89cf7' => 'Reinstalar a los valores predeterminados',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => '¿Eliminar definitivamente el tema <b>%s</b>?<br />Sus disposiciones, configuración y archivos se eliminarán. Esta acción es irreversible.',
	'bc34fea3' => 'Tema %s eliminado',
	'18220db0' => 'Archivo rechazado: contiene una ruta no segura.',
	'ed086de3' => 'Marketplace inaccesible por ahora, inténtalo más tarde.',
	'bded9c78' => 'Todos los addons del marketplace ya están instalados.',
	'96bbd960' => '%d addon(s) disponible(s) en el marketplace. Descargados y verificados (SHA-256) en la instalación.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> no instalado: %s',
	'12996e78' => '<b>%s</b> instalado desde el marketplace',
	'4283c42c' => 'Marketplace inaccesible: no se pueden comprobar las actualizaciones.',
	'10b182db' => '<b>NeoFrag %s</b> está disponible (estás usando %s). Descarga la release y reemplaza los archivos — excepto <code>config/</code>, <code>upload/</code>, <code>backups/</code> — luego visita el sitio (las migraciones se aplican).',
	'd617b951' => 'Todos tus addons están actualizados.',
	'd57a273d' => '%d actualización(es) disponible(s). Descargadas y verificadas (SHA-256) antes de aplicar.',
	'4834bc18' => 'Widget <b>%s</b> no actualizado: %s',
	'a80d96ac' => '<b>%s</b> actualizado a la versión %s',
	'14fc77c5' => 'Ningún nuevo addon detectado en el disco.',
	'8979133d' => '%d addon(s) detectado(s) en el disco. Selecciona los que quieras instalar.',
	'a8ac13ba' => '<b>%s</b> instalado',
	'3fa04ac8' => 'Ningún addon instalado.',
];
