<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Thèmes',
	'2b6a01e8' => 'Veuillez télécharger un thème au format .zip',
	'2b9cde0b' => 'Authentificateurs',
	'3d4e511c' => 'Configuration de <b>%s</b> modifiée',
	'45a26340' => 'Téléchargez un thème .zip (max. %dMo)',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Êtes-vous sûr(e) de vouloir réinstaller le thème <b>%s</b> ?<br />Toutes les dispositions et configurations de widgets seront perdues.',
	'717adbf5' => 'Supprimer le thème',
	'8c65c71b' => '<b>%s</b> activé',
	'8d8bc95c' => '<b>%s</b> désactivé',
	'aa8e1f61' => 'Cette version est déjà installée',
	'b0d653e1' => 'Inactif',
	'b97fd3c7' => 'Personnaliser',
	'bde466c1' => 'Tous',
	'c9340a06' => 'Actif',
	'caf5c873' => 'Actions',
	'ccb3cbb6' => 'Inactifs',
	'd5a02f7c' => 'Thème %s réinstallé par défaut',
	'dbde31be' => 'Liste des thèmes installés',
	'dc275fe4' => 'Filtrer',
	'de200fc5' => 'Langues',
	'e10a7a4b' => 'Modules',
	'e6277648' => 'Une version plus récente de ce thème est déjà installée',
	'f2a45e34' => 'Actifs',
	'fa716ede' => 'Personnalisation du thème',
	'43a89cf7' => 'Réinstaller par défaut',
	'18220db0' => 'Archive refusée : elle contient un chemin non sûr.',
	'ed086de3' => 'Marketplace injoignable pour le moment, réessayez plus tard.',
	'bded9c78' => 'Tous les addons du marketplace sont déjà installés.',
	'96bbd960' => '%d addon(s) disponible(s) sur le marketplace. Téléchargés et vérifiés (SHA-256) à l\'installation.',
	'a475c232' => '<b>%s</b> : %s',
	'995fedc0' => 'Widget <b>%s</b> non installé : %s',
	'12996e78' => '<b>%s</b> installé depuis le marketplace',
	'4283c42c' => 'Marketplace injoignable : impossible de vérifier les mises à jour.',
	'10b182db' => '<b>NeoFrag %s</b> est disponible (tu utilises %s). Télécharge la release et remplace les fichiers — hors <code>config/</code>, <code>upload/</code>, <code>backups/</code> — puis visite le site (les migrations s\'appliquent).',
	'd617b951' => 'Tous vos addons sont à jour.',
	'd57a273d' => '%d mise(s) à jour disponible(s). Téléchargées et vérifiées (SHA-256) avant application.',
	'4834bc18' => 'Widget <b>%s</b> non mis à jour : %s',
	'a80d96ac' => '<b>%s</b> mis à jour en version %s',
	'14fc77c5' => 'Aucun nouvel addon détecté sur le disque.',
	'8979133d' => '%d addon(s) détecté(s) sur le disque. Sélectionnez ceux à installer.',
	'a8ac13ba' => '<b>%s</b> installé',
	'3fa04ac8' => 'Aucun addon installé.',
	'1fc6cce6' => 'Supprimer définitivement le thème <b>%s</b> ?<br />Ses dispositions, sa configuration et ses fichiers seront retirés. Cette action est irréversible.',
	'bc34fea3' => 'Thème %s supprimé',
	'd97a432e' => '<b>%s</b> a besoin de : %s. Installe-les d\'abord.',
	'77a7bf71' => 'Informations',
	'1f86fdde' => 'Thèmes & Addons',
	'ffcc0375' => 'Gestion des modules, widgets, thèmes, langues et authentificateurs installés.',
	'27eee9ef' => 'Authentificateur',
	'eb6693d4' => 'Désactiver',
	'b2b8bdcd' => 'Ordre',
	'635277da' => 'Enregistrez votre site via',
	'c3c7303b' => 'Développement',
	'9cb0b230' => 'Production',
	'94fb70b8' => 'Langue',
	'aa957e20' => 'Préférence des langues',
	'd1871ac3' => 'Thème',
	'a730190a' => 'Supprimer le thème',
	'82551be6' => 'Widget',
	'7810a681' => 'Scanner le disque',
	'fe033a6b' => 'Mises à jour',
	'e0a855b1' => 'Marketplace',
	'0c242628' => 'module',
	'85f91ed0' => 'widget',
	'd62b1ff5' => 'thème',
	'8e49d0be' => 'Le %s %s est déjà installé en version %s',
	'86a093ba' => 'Le %s %s est déjà installé avec une version supérieure',
	'799af6ae' => 'Le %s %s a été installé',
	'c4f5b0f2' => 'Le %s %s a été mis à jour',
	'73667835' => 'Le %s %s n\'a pas pu être installé',
	'5c4047f8' => 'Le %s %s n\'a pas pu être mis à jour',
	'bbf2634a' => 'Le %s %s nécessite la version %s de NeoFrag, veuillez mettre à jour votre site',
	'afb536e2' => 'Le composant ne peut pas être installé, veuillez vérifier la présence des numéros de version',
	'9f2be5d5' => 'Le composant ne peut pas être installé, veuillez vérifier son contenu',
	'8d8a9bda' => '%d Ko',
	'9ed642e7' => 'Mettre à jour',
	'30d19292' => 'authentificateur',
	'9fa5be42' => 'Installer la sélection',
];
