<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Temi',
	'2b6a01e8' => 'Carica un tema in formato .zip',
	'2b9cde0b' => 'Autenticatori',
	'3d4e511c' => 'Configurazione di <b>%s</b> aggiornata',
	'45a26340' => 'Carica un tema .zip (max. %dMB)',
	'52e5dd5d' => 'Widget',
	'53513eff' => 'Sei sicuro di voler reinstallare il tema <b>%s</b>?<br />Tutti i layout e le configurazioni dei widget andranno persi.',
	'717adbf5' => 'Elimina tema',
	'8c65c71b' => '<b>%s</b> attivato',
	'8d8bc95c' => '<b>%s</b> disattivato',
	'aa8e1f61' => 'Questa versione è già installata',
	'b0d653e1' => 'Inattivo',
	'b97fd3c7' => 'Personalizza',
	'bde466c1' => 'Tutti',
	'c9340a06' => 'Attivo',
	'caf5c873' => 'Azioni',
	'ccb3cbb6' => 'Inattivi',
	'd5a02f7c' => 'Tema %s reinstallato ai valori predefiniti',
	'dbde31be' => 'Elenco dei temi installati',
	'dc275fe4' => 'Filtra',
	'de200fc5' => 'Lingue',
	'e10a7a4b' => 'Moduli',
	'e6277648' => 'Una versione più recente di questo tema è già installata',
	'f2a45e34' => 'Attivi',
	'fa716ede' => 'Personalizzazione del tema',
	'43a89cf7' => 'Reinstalla i valori predefiniti',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Eliminare definitivamente il tema <b>%s</b>?<br />Le sue disposizioni, configurazione e file verranno rimossi. Questa azione è irreversibile.',
	'bc34fea3' => 'Tema %s eliminato',
	'18220db0' => 'Archivio rifiutato: contiene un percorso non sicuro.',
	'ed086de3' => 'Marketplace irraggiungibile per ora, riprova più tardi.',
	'bded9c78' => 'Tutti gli addon del marketplace sono già installati.',
	'96bbd960' => '%d addon disponibili sul marketplace. Scaricati e verificati (SHA-256) all\'installazione.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> non installato: %s',
	'12996e78' => '<b>%s</b> installato dal marketplace',
	'4283c42c' => 'Marketplace irraggiungibile: impossibile verificare gli aggiornamenti.',
	'10b182db' => '<b>NeoFrag %s</b> è disponibile (stai usando %s). Scarica la release e sostituisci i file — tranne <code>config/</code>, <code>upload/</code>, <code>backups/</code> — poi visita il sito (le migrazioni vengono applicate).',
	'd617b951' => 'Tutti i tuoi addon sono aggiornati.',
	'd57a273d' => '%d aggiornamento/i disponibili. Scaricati e verificati (SHA-256) prima dell\'applicazione.',
	'4834bc18' => 'Widget <b>%s</b> non aggiornato: %s',
	'a80d96ac' => '<b>%s</b> aggiornato alla versione %s',
	'14fc77c5' => 'Nessun nuovo addon rilevato sul disco.',
	'8979133d' => '%d addon rilevati sul disco. Seleziona quelli da installare.',
	'a8ac13ba' => '<b>%s</b> installato',
	'3fa04ac8' => 'Nessun addon installato.',
];
