<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Temi',
	'2b6a01e8' => 'Carica un tema in formato .zip',
	'2b9cde0b' => 'Autenticatori',
	'3d4e511c' => 'Configurazione di <b>%s</b> aggiornata',
	'45a26340' => 'Carica un tema .zip (max. %dMB)',
	'52e5dd5d' => 'Widget',
	'53513eff' => 'Sei sicuro di voler reinstallare il tema <b>%s</b>?<br />Tutti i layout e le configurazioni dei widget andranno persi.',
	'717adbf5' => 'Elimina tema',
	'8c65c71b' => '<b>%s</b> attivato',
	'8d8bc95c' => '<b>%s</b> disattivato',
	'aa8e1f61' => 'Questa versione è già installata',
	'b0d653e1' => 'Inattivo',
	'b97fd3c7' => 'Personalizza',
	'bde466c1' => 'Tutti',
	'c9340a06' => 'Attivo',
	'caf5c873' => 'Azioni',
	'ccb3cbb6' => 'Inattivi',
	'd5a02f7c' => 'Tema %s reinstallato ai valori predefiniti',
	'dbde31be' => 'Elenco dei temi installati',
	'dc275fe4' => 'Filtra',
	'de200fc5' => 'Lingue',
	'e10a7a4b' => 'Moduli',
	'e6277648' => 'Una versione più recente di questo tema è già installata',
	'f2a45e34' => 'Attivi',
	'fa716ede' => 'Personalizzazione del tema',
	'43a89cf7' => 'Reinstalla i valori predefiniti',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Eliminare definitivamente il tema <b>%s</b>?<br />Le sue disposizioni, configurazione e file verranno rimossi. Questa azione è irreversibile.',
	'bc34fea3' => 'Tema %s eliminato',
	'18220db0' => 'Archivio rifiutato: contiene un percorso non sicuro.',
	'ed086de3' => 'Marketplace irraggiungibile per ora, riprova più tardi.',
	'bded9c78' => 'Tutti gli addon del marketplace sono già installati.',
	'96bbd960' => '%d addon disponibili sul marketplace. Scaricati e verificati (SHA-256) all\'installazione.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> non installato: %s',
	'12996e78' => '<b>%s</b> installato dal marketplace',
	'4283c42c' => 'Marketplace irraggiungibile: impossibile verificare gli aggiornamenti.',
	'10b182db' => '<b>NeoFrag %s</b> è disponibile (stai usando %s). Scarica la release e sostituisci i file — tranne <code>config/</code>, <code>upload/</code>, <code>backups/</code> — poi visita il sito (le migrazioni vengono applicate).',
	'd617b951' => 'Tutti i tuoi addon sono aggiornati.',
	'd57a273d' => '%d aggiornamento/i disponibili. Scaricati e verificati (SHA-256) prima dell\'applicazione.',
	'4834bc18' => 'Widget <b>%s</b> non aggiornato: %s',
	'a80d96ac' => '<b>%s</b> aggiornato alla versione %s',
	'14fc77c5' => 'Nessun nuovo addon rilevato sul disco.',
	'8979133d' => '%d addon rilevati sul disco. Seleziona quelli da installare.',
	'a8ac13ba' => '<b>%s</b> installato',
	'3fa04ac8' => 'Nessun addon installato.',
	'd97a432e' => '<b>%s</b> richiede: %s. Installali prima.',
	'77a7bf71' => 'Informazioni',
	'1f86fdde' => 'Temi & Addons',
	'ffcc0375' => 'Gestione di moduli, widget, temi, lingue e autenticatori installati.',
	'27eee9ef' => 'Autenticatore',
	'eb6693d4' => 'Disattiva',
	'b2b8bdcd' => 'Ordine',
	'635277da' => 'Registra il tuo sito tramite',
	'c3c7303b' => 'Sviluppo',
	'9cb0b230' => 'Produzione',
	'94fb70b8' => 'Lingua',
	'aa957e20' => 'Preferenza delle lingue',
	'd1871ac3' => 'Tema',
	'a730190a' => 'Elimina il tema',
	'82551be6' => 'Widget',
	'7810a681' => 'Scansiona il disco',
	'fe033a6b' => 'Aggiornamenti',
	'e0a855b1' => 'Marketplace',
	'0c242628' => 'modulo',
	'85f91ed0' => 'widget',
	'd62b1ff5' => 'tema',
	'8e49d0be' => 'Il %s %s è già installato nella versione %s',
	'86a093ba' => 'Il %s %s è già installato con una versione superiore',
	'799af6ae' => 'Il %s %s è stato installato',
	'c4f5b0f2' => 'Il %s %s è stato aggiornato',
	'73667835' => 'Non è stato possibile installare il %s %s',
	'5c4047f8' => 'Non è stato possibile aggiornare il %s %s',
	'bbf2634a' => 'Il %s %s richiede la versione %s di NeoFrag, aggiorna il tuo sito',
	'afb536e2' => 'Il componente non può essere installato, verifica la presenza dei numeri di versione',
	'9f2be5d5' => 'Il componente non può essere installato, verificane il contenuto',
	'8d8a9bda' => '%d KB',
	'9ed642e7' => 'Aggiorna',
	'30d19292' => 'autenticatore',
	'9fa5be42' => 'Installa la selezione',
	'2cecf817' => 'Tipo',
	'430d09b2' => 'Cerca un’estensione',
	'e2c8f589' => 'Stato',
	'8088964a' => 'Visualizzazione',
	'3d3305f0' => 'Elenco',
	'd3fe1369' => 'Palinsesto',
	'45002a02' => 'Nessuna estensione corrisponde.',
	'79e64a05' => '<b>NeoFrag %s</b> è disponibile (stai usando %s): <a href="%s">Monitoring</a> lo aggiorna con un clic, con un backup prima di scrivere.',
];
