<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'19b2db1b' => 'Temas',
	'2b6a01e8' => 'Por favor, carregue um tema .zip',
	'2b9cde0b' => 'Autenticadores',
	'3d4e511c' => 'Configuração de <b>%s</b> atualizada',
	'45a26340' => 'Carregar um tema .zip (máx. %dMB)',
	'52e5dd5d' => 'Widgets',
	'53513eff' => 'Tem certeza de que deseja reinstalar o tema <b>%s</b>?<br />Todos os layouts e configurações de widgets serão perdidos.',
	'717adbf5' => 'Eliminar tema',
	'8c65c71b' => '<b>%s</b> ativado',
	'8d8bc95c' => '<b>%s</b> desativado',
	'aa8e1f61' => 'Esta versão já está instalada',
	'b0d653e1' => 'Inativo',
	'b97fd3c7' => 'Personalizar',
	'bde466c1' => 'Todos',
	'c9340a06' => 'Ativo',
	'caf5c873' => 'Ações',
	'ccb3cbb6' => 'Inativos',
	'd5a02f7c' => 'Tema %s reinstalado para os padrões',
	'dbde31be' => 'Lista de temas instalados',
	'dc275fe4' => 'Filtrar',
	'de200fc5' => 'Idiomas',
	'e10a7a4b' => 'Módulos',
	'e6277648' => 'Já está instalada uma versão mais recente deste tema',
	'f2a45e34' => 'Ativos',
	'fa716ede' => 'A personalizar tema',
	'43a89cf7' => 'Reinstalar para os padrões',
	// i18n 2026-06-11 (code strings)
	'1fc6cce6' => 'Eliminar definitivamente o tema <b>%s</b>?<br />As suas disposições, configuração e ficheiros serão removidos. Esta ação é irreversível.',
	'bc34fea3' => 'Tema %s eliminado',
	'18220db0' => 'Arquivo recusado: contém um caminho não seguro.',
	'ed086de3' => 'Marketplace inacessível de momento, tenta mais tarde.',
	'bded9c78' => 'Todos os addons do marketplace já estão instalados.',
	'96bbd960' => '%d addon(s) disponível(eis) no marketplace. Descarregados e verificados (SHA-256) na instalação.',
	'a475c232' => '<b>%s</b>: %s',
	'995fedc0' => 'Widget <b>%s</b> não instalado: %s',
	'12996e78' => '<b>%s</b> instalado a partir do marketplace',
	'4283c42c' => 'Marketplace inacessível: não é possível verificar atualizações.',
	'10b182db' => '<b>NeoFrag %s</b> está disponível (estás a usar %s). Descarrega a release e substitui os ficheiros — exceto <code>config/</code>, <code>upload/</code>, <code>backups/</code> — depois visita o site (as migrações aplicam-se).',
	'd617b951' => 'Todos os teus addons estão atualizados.',
	'd57a273d' => '%d atualização(ões) disponível(eis). Descarregadas e verificadas (SHA-256) antes de aplicar.',
	'4834bc18' => 'Widget <b>%s</b> não atualizado: %s',
	'a80d96ac' => '<b>%s</b> atualizado para a versão %s',
	'14fc77c5' => 'Nenhum novo addon detetado no disco.',
	'8979133d' => '%d addon(s) detetado(s) no disco. Seleciona os que queres instalar.',
	'a8ac13ba' => '<b>%s</b> instalado',
	'3fa04ac8' => 'Nenhum addon instalado.',
];
