<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'1ea90f79' => 'Schließen',
	'2b8be5d7' => 'Mehrdeutigkeiten zu beheben',
	'2d25f98e' => 'Gruppe ausgeschlossen',
	'349b63bb' => 'Gruppe berechtigt',
	'45234b85' => 'Berechtigungsliste',
	'514aeaa6' => 'Benutzer',
	'54231355' => 'Name',
	'599dba10' => 'Zurücksetzen',
	'86c33902' => 'Bearbeiten',
	'98de5f45' => 'Gruppen',
	'ab7143b8' => 'Berechtigungen',
	'befc1364' => 'Zugriff',
	'c2ab6390' => 'Berechtigungsverwaltung',
	'ceae385f' => 'Mitglied ausgeschlossen',
	'd90775ec' => 'Es gibt keine zu verwaltenden Berechtigungen',
	'db6ab372' => 'Mitglied',
	'ec006b78' => 'Alle Berechtigungen zurücksetzen',
	'ed61e9ab' => 'Auf automatisch zurücksetzen',
	'f118fe1f' => 'Mitglied',
	'f7a14c05' => 'Auf Modul %s zugreifen',
	// i18n 2026-06-11 (code strings)
	'8084a5c2' => 'Berechtigungen — Matrixansicht',
	'ef840f27' => 'Modul wählen',
	'f05f763b' => 'Modul wechseln',
	'20f20251' => 'Berechtigungen von %s',
	'3f88dac6' => 'Verwaltung der Rollen und ihrer Berechtigungen',
	'fa506601' => 'Rolle erstellen',
	'421b8d8a' => 'Rollenliste',
	'049fa80d' => 'Neue Rolle',
	'93ac810f' => 'Rolle „%s" erstellt',
	'dcf68579' => 'Berechtigungen konfigurieren',
	'0f2cbb2f' => 'Rolle „%s" aktualisiert',
	'4824e025' => 'Diese Rolle kann nicht geändert werden (integriert oder nicht vorhanden)',
	'ebffa3e9' => '„%s" bearbeiten',
	'691462c3' => 'Eine integrierte Rolle kann nicht gelöscht werden (super_admin, member, visitor)',
	'df7483d7' => 'Rolle „%s" gelöscht',
	'c0d7015a' => 'Löschen fehlgeschlagen',
	'9b189791' => 'Rolle klonen',
	'9dcb4f77' => 'Technischer Name der neuen Rolle',
	'4ddaabbb' => 'Interne Kennung (Buchstaben, Ziffern, _ und -). Muss eindeutig sein.',
	'cc658cec' => 'Angezeigter Titel',
	'e341cda0' => 'Klonen',
	'dc04070b' => 'Der Name „%s" existiert bereits, wähle einen anderen',
	'e8637580' => 'Rolle erfolgreich geklont',
	'eaeb8ea6' => 'Klonen fehlgeschlagen',
	'1227bee3' => '„%s" klonen',
	'dd0db25b' => 'Benutzern Rollen zuweisen',
	'5c555834' => 'Matrix Benutzer × Rollen',
	'1c6cf280' => 'Benutzer × Rollen',
	'eb2bcec3' => 'Gruppen Rollen zuweisen',
	'21c49fe8' => 'Matrix Gruppen × Rollen',
	'3005a173' => 'Gruppen × Rollen',
	'18ac1470' => 'Vorschaumodus aktiviert: Du siehst die Website als Rolle „%s"',
	'3818d2e0' => 'Vorschaumodus aktiviert: Du siehst die Website als %s',
	'93795f1e' => 'Vorschaumodus deaktiviert. Du siehst die Website wieder mit deinen eigenen Berechtigungen.',
	'ff7ae482' => 'Effektive Berechtigungen',
	'a3e756b7' => 'Zuweisungen',
	'fba06471' => 'Effektive Berechtigungen von %s',
	'c6fb796d' => 'Die Vorschau der super_admin-Rolle ist nutzlos (gleiches Verhalten wie dein aktueller Zugriff).',
	'f7f67ce0' => 'Technischer Name',
	'714d4678' => 'Interne Kennung (Buchstaben, Ziffern, _ und -). Z. B. "moderator_lead". Muss eindeutig sein.',
	'56fa5a2d' => 'Sichtbar in der Verwaltung und auf Profilen.',
	'7836078f' => 'Optional. Kurze Notiz, um zu erklären, wofür diese Rolle dient.',
	'e337fd0b' => 'Für die Anzeige in der Verwaltung.',
	'b96a36d0' => 'Primary (blau)',
	'186d0243' => 'Secondary (grau)',
	'677384b9' => 'Success (grün)',
	'1831c942' => 'Danger (rot)',
	'a2d5df87' => 'Warning (orange)',
	'3320cb62' => 'Info (cyan)',
	'195f0078' => 'Dark (schwarz)',
	'5a439a59' => 'Light (weiß)',
	'b90c3bbb' => 'Font-Awesome-Klasse. Z. B. "fas fa-user-shield".',
	'0a0d4f32' => 'Erbt von',
	'16f0b201' => 'Die übergeordnete Rolle, deren Berechtigungen automatisch geerbt werden. Optional.',
	'e76d95dd' => 'Integrierte Rollen haben keinen bearbeitbaren Elternteil.',
	'32f5a0f6' => 'Keine persistente Gruppe in der DB. Die automatischen Gruppen (admins/members/visitors) sind hier nicht konfigurierbar — sie werden direkt den integrierten Rollen super_admin/member/visitor zugeordnet.',
	'7f1008e8' => 'Das Zuweisen einer Rolle an eine Gruppe gibt sie automatisch allen ihren Mitgliedern. Praktisch für Bulk: Füge einen Benutzer zur Gruppe hinzu → er erbt die Rollen.',
	'95fb5749' => 'Modul: <strong>%s</strong>',
	'923c1403' => 'Geltungsbereich %d',
	'9422af16' => 'Grün = erlaubt, Rot = nie (Override-Block), Grau = Standard. Geerbte Werte sind mit ↓ markiert.',
	'af14917a' => 'Berechtigung',
	'989423c8' => 'Geerbt von %s',
	'47f2a4f7' => 'Über Wildcard %s.*',
	'1fdf8774' => 'Erlauben',
	'0f93c639' => 'Standard (kein Override)',
	'05fcab64' => 'Nie (Override-Block)',
	'd0f64060' => 'Kein Modul deklariert Berechtigungen.',
	'89c99745' => 'Wähle ein Modul, um seine Berechtigungen pro Rolle zu verwalten:',
	'e7acb55a' => 'Keine Rolle. Erstelle die erste über die Schaltfläche oben.',
	'dbfdeb78' => 'In der Matrix konfigurieren',
	'a55db3c6' => 'Systemrolle, nicht löschbar',
	'090e5f62' => 'Built-in',
	'5023c3f4' => 'Benutzerdefiniert',
	'cbb0c23f' => 'Vorschaumodus „als %s anzeigen" aktivieren? Du siehst die Website mit den Berechtigungen dieser Rolle (nicht mehr mit deinem Super-Admin-Zugriff), bis du auf „Verlassen" klickst.',
	'daac885d' => 'Als diese Rolle anzeigen',
	'390fa25b' => 'Die Website als diese Rolle anzeigen',
	'916776d2' => 'Die Rolle „%s" löschen? Alle ihre %d Benutzer verlieren diese Berechtigungen.',
	'bd8c94ae' => 'Rolle löschen',
	'68feb107' => 'Integriert, nicht löschbar',
	'54c03d45' => 'Kein Benutzer.',
	'937d053d' => 'Ankreuzen, um eine Rolle zuzuweisen. Änderungen werden automatisch gespeichert. Der <code>nf_user.admin=1</code>-Bypass umgeht immer das System und gewährt alle Rechte.',
	'49ce3e3e' => 'Admin-Bypass aktiv',
	'8e6bd3cd' => 'Diese Seite listet die <strong>effektiven</strong> Berechtigungen von %s auf — d. h. was er <em>wirklich</em> tun kann, unter Berücksichtigung seiner direkten Rollen, der Rollen über seine Gruppen, der Vererbung und des Admin-Bypass, falls aktiv.',
	'1541b0fb' => 'Vorschaumodus „als %s anzeigen" aktivieren? Du siehst die Website mit seinen Berechtigungen, seinem Admin-Status usw.',
	'23511ca0' => 'Als diesen Benutzer anzeigen',
	'f188f11a' => 'Als diesen Benutzer anzeigen',
	'0e519629' => 'Dieser Benutzer hat das Flag <code>nf_user.admin=1</code> — er hat über den Super-Admin-Bypass Zugriff auf <strong>alle</strong> Berechtigungen, unabhängig von der Liste unten.',
	'88880241' => 'Keine effektive Berechtigung. Dieser Benutzer hat weder direkt noch über seine Gruppen eine Rolle zugewiesen.',
	'c16e7ad7' => 'Geltungsbereich',
	'1ce8c867' => 'Wert',
	'f14f39cf' => 'Quelle (Rolle)',
	'e8058b83' => 'global',
];
