<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'1ea90f79' => 'Cerrar',
	'2b8be5d7' => 'Ambigüedades a corregir',
	'2d25f98e' => 'Grupo excluido',
	'349b63bb' => 'Grupo autorizado',
	'45234b85' => 'Lista de permisos',
	'514aeaa6' => 'Usuarios',
	'54231355' => 'Nombre',
	'599dba10' => 'Restablecer',
	'86c33902' => 'Editar',
	'98de5f45' => 'Grupos',
	'ab7143b8' => 'Permisos',
	'befc1364' => 'Acceso',
	'c2ab6390' => 'Gestión de permisos',
	'ceae385f' => 'Miembro excluido',
	'd90775ec' => 'No hay permisos para gestionar',
	'db6ab372' => 'Miembro',
	'ec006b78' => 'Restablecer todos los permisos',
	'ed61e9ab' => 'Volver a automático',
	'f118fe1f' => 'Miembro',
	'f7a14c05' => 'Acceder al módulo %s',
	// i18n 2026-06-11 (code strings)
	'8084a5c2' => 'Permisos — Vista matricial',
	'ef840f27' => 'Elegir un módulo',
	'f05f763b' => 'Cambiar de módulo',
	'20f20251' => 'Permisos de %s',
	'3f88dac6' => 'Gestión de los roles y sus permisos',
	'fa506601' => 'Crear un rol',
	'421b8d8a' => 'Lista de roles',
	'049fa80d' => 'Nuevo rol',
	'93ac810f' => 'Rol "%s" creado',
	'dcf68579' => 'Configurar los permisos',
	'0f2cbb2f' => 'Rol "%s" actualizado',
	'4824e025' => 'No se puede modificar este rol (built-in o inexistente)',
	'ebffa3e9' => 'Editar "%s"',
	'691462c3' => 'No se puede eliminar un rol built-in (super_admin, member, visitor)',
	'df7483d7' => 'Rol "%s" eliminado',
	'c0d7015a' => 'Eliminación fallida',
	'9b189791' => 'Clonar el rol',
	'9dcb4f77' => 'Nombre técnico del nuevo rol',
	'4ddaabbb' => 'Identificador interno (letras, números, _ y -). Debe ser único.',
	'cc658cec' => 'Título mostrado',
	'e341cda0' => 'Clonar',
	'dc04070b' => 'El nombre "%s" ya existe, elige otro',
	'e8637580' => 'Rol clonado con éxito',
	'eaeb8ea6' => 'Clonación fallida',
	'1227bee3' => 'Clonar "%s"',
	'dd0db25b' => 'Asignar roles a los usuarios',
	'5c555834' => 'Matriz usuarios × roles',
	'1c6cf280' => 'Usuarios × Roles',
	'eb2bcec3' => 'Asignar roles a los grupos',
	'21c49fe8' => 'Matriz grupos × roles',
	'3005a173' => 'Grupos × Roles',
	'18ac1470' => 'Modo vista previa activado: ves el sitio como el rol "%s"',
	'3818d2e0' => 'Modo vista previa activado: ves el sitio como %s',
	'93795f1e' => 'Modo vista previa desactivado. Vuelves a ver el sitio con tus propios permisos.',
	'ff7ae482' => 'Permisos efectivos',
	'a3e756b7' => 'Asignaciones',
	'fba06471' => 'Permisos efectivos de %s',
	'c6fb796d' => 'La vista previa del rol super_admin es inútil (mismo comportamiento que tu acceso actual).',
	'f7f67ce0' => 'Nombre técnico',
	'714d4678' => 'Identificador interno (letras, números, _ y -). Ej. "moderator_lead". Debe ser único.',
	'56fa5a2d' => 'Visible en la administración y en los perfiles.',
	'7836078f' => 'Opcional. Nota breve para explicar para qué sirve este rol.',
	'e337fd0b' => 'Para mostrar en la administración.',
	'b96a36d0' => 'Primary (azul)',
	'186d0243' => 'Secondary (gris)',
	'677384b9' => 'Success (verde)',
	'1831c942' => 'Danger (rojo)',
	'a2d5df87' => 'Warning (naranja)',
	'3320cb62' => 'Info (cian)',
	'195f0078' => 'Dark (negro)',
	'5a439a59' => 'Light (blanco)',
	'b90c3bbb' => 'Clase Font Awesome. Ej. "fas fa-user-shield".',
	'0a0d4f32' => 'Hereda de',
	'16f0b201' => 'El rol padre cuyos permisos se heredan automáticamente. Opcional.',
	'e76d95dd' => 'Los roles built-in no tienen un padre editable.',
	'32f5a0f6' => 'Ningún grupo persistente en la BD. Los grupos automáticos (admins/members/visitors) no se pueden configurar aquí — se asignan directamente a los roles built-in super_admin/member/visitor.',
	'7f1008e8' => 'Asignar un rol a un grupo se lo da automáticamente a todos sus miembros. Práctico para lotes: añade un usuario al grupo → hereda los roles.',
	'95fb5749' => 'Módulo: <strong>%s</strong>',
	'923c1403' => 'Ámbito %d',
	'9422af16' => 'Verde = permitido, Rojo = nunca (override-block), Gris = predeterminado. Los valores heredados se marcan con ↓.',
	'af14917a' => 'Permiso',
	'989423c8' => 'Heredado de %s',
	'47f2a4f7' => 'Vía comodín %s.*',
	'1fdf8774' => 'Permitir',
	'0f93c639' => 'Predeterminado (sin override)',
	'05fcab64' => 'Nunca (override-block)',
	'd0f64060' => 'Ningún módulo declara permisos.',
	'89c99745' => 'Selecciona un módulo para gestionar sus permisos por rol:',
	'e7acb55a' => 'Ningún rol. Crea el primero con el botón de arriba.',
	'dbfdeb78' => 'Configurar en la matriz',
	'a55db3c6' => 'Rol del sistema, no eliminable',
	'090e5f62' => 'Built-in',
	'5023c3f4' => 'Personalizado',
	'cbb0c23f' => '¿Activar el modo vista previa "ver como %s"? Verás el sitio con los permisos de este rol (ya no con tu acceso de superadministrador) hasta que hagas clic en "Salir".',
	'daac885d' => 'Ver como este rol',
	'390fa25b' => 'Ver el sitio como este rol',
	'916776d2' => '¿Eliminar el rol "%s"? Sus %d usuarios perderán estos permisos.',
	'bd8c94ae' => 'Eliminar el rol',
	'68feb107' => 'Built-in, no eliminable',
	'54c03d45' => 'Ningún usuario.',
	'937d053d' => 'Marca para asignar un rol. Los cambios se guardan automáticamente. El bypass <code>nf_user.admin=1</code> siempre cortocircuita el sistema y concede todos los derechos.',
	'49ce3e3e' => 'Bypass de admin activo',
	'8e6bd3cd' => 'Esta página lista los permisos <strong>efectivos</strong> de %s — es decir, lo que <em>realmente</em> puede hacer teniendo en cuenta sus roles directos, los roles vía sus grupos, la herencia y el bypass de admin si está activo.',
	'1541b0fb' => '¿Activar el modo vista previa "ver como %s"? Verás el sitio con sus permisos, su estado de admin, etc.',
	'23511ca0' => 'Ver como este usuario',
	'f188f11a' => 'Ver como este usuario',
	'0e519629' => 'Este usuario tiene el flag <code>nf_user.admin=1</code> — tiene acceso a <strong>todos</strong> los permisos vía el bypass de superadministrador, independientemente de la lista de abajo.',
	'88880241' => 'Ningún permiso efectivo. Este usuario no tiene ningún rol asignado directamente ni vía sus grupos.',
	'c16e7ad7' => 'Ámbito',
	'1ce8c867' => 'Valor',
	'f14f39cf' => 'Origen (rol)',
	'e8058b83' => 'global',
];
