<?php
/**
 * https://translate.neofr.ag
 * @author: NeoFrag — i18n sync 2026-05-03
 */

return [
	'1ea90f79' => 'Fechar',
	'2b8be5d7' => 'Ambiguidades a corrigir',
	'2d25f98e' => 'Grupo excluído',
	'349b63bb' => 'Grupo autorizado',
	'45234b85' => 'Lista de permissões',
	'514aeaa6' => 'Utilizadores',
	'54231355' => 'Nome',
	'599dba10' => 'Redefinir',
	'86c33902' => 'Editar',
	'98de5f45' => 'Grupos',
	'ab7143b8' => 'Permissões',
	'befc1364' => 'Acesso',
	'c2ab6390' => 'Gestão de permissões',
	'ceae385f' => 'Membro excluído',
	'd90775ec' => 'Não há permissões para gerir',
	'db6ab372' => 'Membro',
	'ec006b78' => 'Repor todas as permissões',
	'ed61e9ab' => 'Redefinir para automático',
	'f118fe1f' => 'Membro',
	'f7a14c05' => 'Acessar módulo %s',
	// i18n 2026-06-11 (code strings)
	'8084a5c2' => 'Permissões — Vista matricial',
	'ef840f27' => 'Escolher um módulo',
	'f05f763b' => 'Mudar de módulo',
	'20f20251' => 'Permissões de %s',
	'3f88dac6' => 'Gestão dos papéis e das suas permissões',
	'fa506601' => 'Criar um papel',
	'421b8d8a' => 'Lista de papéis',
	'049fa80d' => 'Novo papel',
	'93ac810f' => 'Papel "%s" criado',
	'dcf68579' => 'Configurar as permissões',
	'0f2cbb2f' => 'Papel "%s" atualizado',
	'4824e025' => 'Não é possível modificar este papel (built-in ou inexistente)',
	'ebffa3e9' => 'Editar "%s"',
	'691462c3' => 'Não é possível eliminar um papel built-in (super_admin, member, visitor)',
	'df7483d7' => 'Papel "%s" eliminado',
	'c0d7015a' => 'Eliminação falhou',
	'9b189791' => 'Clonar o papel',
	'9dcb4f77' => 'Nome técnico do novo papel',
	'4ddaabbb' => 'Identificador interno (letras, números, _ e -). Deve ser único.',
	'cc658cec' => 'Título apresentado',
	'e341cda0' => 'Clonar',
	'dc04070b' => 'O nome "%s" já existe, escolhe outro',
	'e8637580' => 'Papel clonado com sucesso',
	'eaeb8ea6' => 'Clonagem falhou',
	'1227bee3' => 'Clonar "%s"',
	'dd0db25b' => 'Atribuir papéis aos utilizadores',
	'5c555834' => 'Matriz utilizadores × papéis',
	'1c6cf280' => 'Utilizadores × Papéis',
	'eb2bcec3' => 'Atribuir papéis aos grupos',
	'21c49fe8' => 'Matriz grupos × papéis',
	'3005a173' => 'Grupos × Papéis',
	'18ac1470' => 'Modo de pré-visualização ativado: vês o site como o papel "%s"',
	'3818d2e0' => 'Modo de pré-visualização ativado: vês o site como %s',
	'93795f1e' => 'Modo de pré-visualização desativado. Vês novamente o site com as tuas próprias permissões.',
	'ff7ae482' => 'Permissões efetivas',
	'a3e756b7' => 'Atribuições',
	'fba06471' => 'Permissões efetivas de %s',
	'c6fb796d' => 'A pré-visualização do papel super_admin é inútil (mesmo comportamento que o teu acesso atual).',
	'f7f67ce0' => 'Nome técnico',
	'714d4678' => 'Identificador interno (letras, números, _ e -). Ex. "moderator_lead". Deve ser único.',
	'56fa5a2d' => 'Visível na administração e nos perfis.',
	'7836078f' => 'Opcional. Nota breve para explicar para que serve este papel.',
	'e337fd0b' => 'Para apresentação na administração.',
	'b96a36d0' => 'Primary (azul)',
	'186d0243' => 'Secondary (cinzento)',
	'677384b9' => 'Success (verde)',
	'1831c942' => 'Danger (vermelho)',
	'a2d5df87' => 'Warning (laranja)',
	'3320cb62' => 'Info (ciano)',
	'195f0078' => 'Dark (preto)',
	'5a439a59' => 'Light (branco)',
	'b90c3bbb' => 'Classe Font Awesome. Ex. "fas fa-user-shield".',
	'0a0d4f32' => 'Herda de',
	'16f0b201' => 'O papel pai cujas permissões são herdadas automaticamente. Opcional.',
	'e76d95dd' => 'Os papéis built-in não têm um pai editável.',
	'32f5a0f6' => 'Nenhum grupo persistente na BD. Os grupos automáticos (admins/members/visitors) não são configuráveis aqui — são mapeados diretamente para os papéis built-in super_admin/member/visitor.',
	'7f1008e8' => 'Atribuir um papel a um grupo dá-o automaticamente a todos os seus membros. Prático para bulk: adiciona um utilizador ao grupo → herda os papéis.',
	'95fb5749' => 'Módulo: <strong>%s</strong>',
	'923c1403' => 'Âmbito %d',
	'9422af16' => 'Verde = permitido, Vermelho = nunca (override-block), Cinzento = predefinido. Os valores herdados são marcados com ↓.',
	'af14917a' => 'Permissão',
	'989423c8' => 'Herdado de %s',
	'47f2a4f7' => 'Via wildcard %s.*',
	'1fdf8774' => 'Permitir',
	'0f93c639' => 'Predefinido (sem override)',
	'05fcab64' => 'Nunca (override-block)',
	'd0f64060' => 'Nenhum módulo declara permissões.',
	'89c99745' => 'Seleciona um módulo para gerir as suas permissões por papel:',
	'e7acb55a' => 'Nenhum papel. Cria o primeiro com o botão acima.',
	'dbfdeb78' => 'Configurar na matriz',
	'a55db3c6' => 'Papel de sistema, não eliminável',
	'090e5f62' => 'Built-in',
	'5023c3f4' => 'Personalizado',
	'cbb0c23f' => 'Ativar o modo de pré-visualização "ver como %s"? Verás o site com as permissões deste papel (já não com o teu acesso de super-admin) até clicares em "Sair".',
	'daac885d' => 'Ver como este papel',
	'390fa25b' => 'Ver o site como este papel',
	'916776d2' => 'Eliminar o papel "%s"? Todos os seus %d utilizadores perderão estas permissões.',
	'bd8c94ae' => 'Eliminar o papel',
	'68feb107' => 'Built-in, não eliminável',
	'54c03d45' => 'Nenhum utilizador.',
	'937d053d' => 'Marca para atribuir um papel. As alterações são guardadas automaticamente. O bypass <code>nf_user.admin=1</code> curto-circuita sempre o sistema e concede todos os direitos.',
	'49ce3e3e' => 'Bypass de admin ativo',
	'8e6bd3cd' => 'Esta página lista as permissões <strong>efetivas</strong> de %s — ou seja, o que pode <em>realmente</em> fazer tendo em conta os seus papéis diretos, os papéis através dos seus grupos, a herança e o bypass de admin se ativo.',
	'1541b0fb' => 'Ativar o modo de pré-visualização "ver como %s"? Verás o site com as permissões dele, o seu estado de admin, etc.',
	'23511ca0' => 'Ver como este utilizador',
	'f188f11a' => 'Ver como este utilizador',
	'0e519629' => 'Este utilizador tem a flag <code>nf_user.admin=1</code> — tem acesso a <strong>todas</strong> as permissões via o bypass de super-admin, independentemente da lista abaixo.',
	'88880241' => 'Nenhuma permissão efetiva. Este utilizador não tem nenhum papel atribuído diretamente nem através dos seus grupos.',
	'c16e7ad7' => 'Âmbito',
	'1ce8c867' => 'Valor',
	'f14f39cf' => 'Origem (papel)',
	'e8058b83' => 'global',
];
