<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'Die REST-API der Website: Zugangsschlüssel für Programme (der Discord-Bot, eine Integration), versionierte Adressen, die JSON liefern.',
	'8b488245' => 'Zugangsschlüssel verwalten',
	'5bcb4267' => 'Mitglieder und Gruppen lesen',
	'94a604be' => 'Das Forum lesen',
	'4639a8f5' => 'Nie',
	'4cb2f934' => 'Aktiv',
	'559e8608' => 'Widerrufen',
	'e82fd19a' => 'Diesen Schlüssel widerrufen? Das Programm, das ihn nutzt, verliert sofort den Zugang.',
	'7d9647c7' => 'Widerrufen',
	'a6f5854a' => 'Schlüssel',
	'0005d1f8' => 'Rechte',
	'a9888d2f' => 'Zuletzt genutzt',
	'80b0b3e8' => 'Status',
	'1a476e67' => 'Noch keine Zugangsschlüssel.',
	'd5f8720d' => 'Ein Schlüssel erlaubt einem Programm — dem Discord-Bot, einer Integration —, über die API auf der Website zu lesen oder zu schreiben, nur mit den Rechten, die Sie ihm geben.',
	'5ba5fc51' => 'Adresse der API: %s — jede Anfrage trägt den Header %s.',
	'fe916ce8' => 'Zugangsschlüssel',
	'05263085' => 'Neuer Schlüssel',
	'e1410c8a' => 'Um den Schlüssel wiederzuerkennen: „Discord-Bot“, „Team-Integration“…',
	'2a5c2d55' => 'Geben Sie nur die Rechte, die das Programm braucht.',
	'e2d08a3c' => 'Schlüssel erstellen',
	'f789c08b' => 'Schlüssel erstellt',
	'9dc59300' => 'Kopieren Sie diesen Schlüssel jetzt: Er wird nie wieder angezeigt. Wenn Sie ihn verlieren, widerrufen Sie ihn und erstellen Sie einen neuen.',
	'84a6d968' => 'Zugangsschlüssel',
	'a080ab79' => 'Zurück zu den Schlüsseln',
	'339cadad' => 'Schlüssel widerrufen.',
	'fe667d1b' => 'Zu viele Anfragen. Versuchen Sie es später erneut.',
	'619618bc' => 'Zugangsschlüssel fehlt, ist ungültig oder widerrufen.',
	'd129aab8' => 'Dieser Schlüssel hat nicht das Recht „%s“.',
	'fa0787ba' => 'Methode an dieser Adresse nicht erlaubt.',
	'569e32bc' => 'Unbekannte API-Adresse.',
	'25d8c6f6' => 'Mitglied nicht gefunden.',
	'd507cfac' => 'Kein Mitglied hat dieses Discord-Konto verknüpft.',
	'240cfde5' => 'Das Forum ist auf dieser Website nicht installiert.',
	'8d3f0801' => 'Dem Ereignis-Feed folgen',
	'39fde08d' => 'Thema nicht gefunden.',
	'740e4d7e' => 'Nachricht nicht gefunden.',
	'14452488' => 'Im Forum im Namen eines Mitglieds oder eines Discord-Kontos schreiben',
	'36aed174' => 'Unbekanntes Forum.',
	'04fbbb26' => 'Dieses Forum ist ein Link zu einer externen Adresse.',
	'01f6d1f0' => '1 bis %d Zeichen.',
	'd24c4896' => 'Unbekanntes Präfix.',
	'b4369901' => 'Dieses Thema ist gesperrt.',
	'80938f81' => 'Die erste Nachricht eines Themas kann nicht über die API gelöscht werden.',
	'd4d5187a' => 'Von einem mit der Website verbundenen Programm gelöscht (API).',
	'39824a6f' => 'Nur der Autor dieser Nachricht kann sie über die API bearbeiten oder löschen.',
	'9e49da1d' => 'Ein Autor wird erwartet: author.member_id oder author.discord mit seiner ID (eine Zahl) und seinem username.',
	'df7fef5b' => '„markdown“ oder „html“.',
	'3eb6574b' => 'Der Inhalt ist nach der Bereinigung leer.',
	'd5e9c4a6' => 'Der Anfragetext ist kein gültiges JSON.',
	'b2ee4e4b' => 'Einige Felder sind ungültig.',
	'7cb47b88' => 'Der Discord-Bot der Website sein (seine Konfiguration, einschließlich seines Discord-Schlüssels)',
	'3a8dd48c' => 'Das Discord-Modul ist auf dieser Website nicht installiert.',
	'a1a0582d' => 'Keine Verknüpfung für dieses Element.',
	'471ee58d' => 'Dieses Discord-Konto ist mit keinem Mitglied verknüpft.',
	'194eb50d' => 'Dieses Discord-Konto ist die einzige Anmeldemöglichkeit seines Mitglieds.',
	'4842e199' => 'Dieses Discord-Konto ist verknüpft: Es veröffentlicht unter seinem Mitglied.',
	'5e59fa20' => 'Den Bugtracker lesen',
	'7c49265e' => 'In den Bugtracker schreiben: ein Ticket eröffnen, kommentieren, im Namen eines Mitglieds oder eines Discord-Kontos',
	'4ca1a22c' => 'Ticket nicht gefunden.',
	'a771a710' => 'Kommentar nicht gefunden.',
	'32cb210b' => 'Ein Ticket gehört einem Mitglied: Dieses Discord-Konto muss zuerst verknüpft werden.',
	'f7232257' => 'Nur der Autor dieses Kommentars kann ihn über die API bearbeiten oder löschen.',
	'31a19f58' => 'Der Bugtracker ist auf dieser Website nicht installiert.',
	'38ce3464' => 'Diese Rolle ist mit einer Gruppe der Website verknüpft: Die Gruppensynchronisierung vergibt und entfernt sie bereits.',
	'fc49b15e' => 'Dieser Autor darf in diesem Forum nicht schreiben.',
];
