<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'The site\'s REST API: access keys for programs (the Discord bot, an integration), versioned addresses that return JSON.',
	'8b488245' => 'Manage access keys',
	'5bcb4267' => 'Read members and groups',
	'94a604be' => 'Read the forum',
	'4639a8f5' => 'Never',
	'4cb2f934' => 'Active',
	'559e8608' => 'Revoked',
	'e82fd19a' => 'Revoke this key? The program using it will lose access immediately.',
	'7d9647c7' => 'Revoke',
	'a6f5854a' => 'Key',
	'0005d1f8' => 'Permissions',
	'a9888d2f' => 'Last used',
	'80b0b3e8' => 'Status',
	'1a476e67' => 'No access keys yet.',
	'd5f8720d' => 'A key lets a program — the Discord bot, an integration — read or write on the site through the API, with only the permissions you give it.',
	'5ba5fc51' => 'API address: %s — every request carries the header %s.',
	'fe916ce8' => 'Access keys',
	'05263085' => 'New key',
	'e1410c8a' => 'To recognize the key: “Discord bot”, “Team integration”…',
	'2a5c2d55' => 'Only give the permissions the program needs.',
	'e2d08a3c' => 'Create the key',
	'f789c08b' => 'Key created',
	'9dc59300' => 'Copy this key now: it will never be shown again. If you lose it, revoke it and create another one.',
	'84a6d968' => 'Access key',
	'a080ab79' => 'Back to keys',
	'339cadad' => 'Key revoked.',
	'fe667d1b' => 'Too many requests. Try again later.',
	'619618bc' => 'Access key missing, invalid or revoked.',
	'd129aab8' => 'This key does not have the “%s” permission.',
	'fa0787ba' => 'Method not allowed on this address.',
	'569e32bc' => 'Unknown API address.',
	'25d8c6f6' => 'Member not found.',
	'd507cfac' => 'No member has linked this Discord account.',
	'240cfde5' => 'The forum is not installed on this site.',
	'8d3f0801' => 'Follow the event feed',
	'39fde08d' => 'Topic not found.',
	'740e4d7e' => 'Message not found.',
	'14452488' => 'Write on the forum on behalf of a member or a Discord account',
	'36aed174' => 'Unknown forum.',
	'04fbbb26' => 'This forum is a link to an external address.',
	'01f6d1f0' => 'From 1 to %d characters.',
	'd24c4896' => 'Unknown prefix.',
	'b4369901' => 'This topic is locked.',
	'80938f81' => 'The first message of a topic cannot be deleted through the API.',
	'd4d5187a' => 'Deleted from a program linked to the site (API).',
	'39824a6f' => 'Only the author of this message can edit or delete it through the API.',
	'9e49da1d' => 'An author is expected: author.member_id, or author.discord with its id (a number) and its username.',
	'df7fef5b' => '“markdown” or “html”.',
	'3eb6574b' => 'The content is empty once cleaned.',
	'd5e9c4a6' => 'The request body is not valid JSON.',
	'b2ee4e4b' => 'Some fields are invalid.',
	'7cb47b88' => 'Be the site’s Discord bot (its configuration, including its Discord key)',
	'3a8dd48c' => 'The Discord module is not installed on this site.',
	'a1a0582d' => 'No link for this item.',
	'471ee58d' => 'This Discord account is not linked to any member.',
	'194eb50d' => 'This Discord account is its member’s only way to log in.',
	'4842e199' => 'This Discord account is linked: it posts under its member.',
	'5e59fa20' => 'Read the Bugtracker',
	'7c49265e' => 'Write to the Bugtracker: open a ticket, comment, on behalf of a member or a Discord account',
	'4ca1a22c' => 'Ticket not found.',
	'a771a710' => 'Comment not found.',
	'32cb210b' => 'A ticket belongs to a member: this Discord account must be linked first.',
	'f7232257' => 'Only the author of this comment can edit or delete it through the API.',
	'31a19f58' => 'The Bugtracker is not installed on this site.',
	'38ce3464' => 'This role is linked to a site group: the group sync already gives and removes it.',
	'fc49b15e' => 'This author is not allowed to write in this forum.',
];
