<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'La API REST del sitio: claves de acceso para programas (el bot de Discord, una integración), direcciones versionadas que devuelven JSON.',
	'8b488245' => 'Gestionar las claves de acceso',
	'5bcb4267' => 'Leer los miembros y los grupos',
	'94a604be' => 'Leer el foro',
	'4639a8f5' => 'Nunca',
	'4cb2f934' => 'Activo',
	'559e8608' => 'Revocada',
	'e82fd19a' => '¿Revocar esta clave? El programa que la usa perderá el acceso de inmediato.',
	'7d9647c7' => 'Revocar',
	'a6f5854a' => 'Clave',
	'0005d1f8' => 'Permisos',
	'a9888d2f' => 'Último uso',
	'80b0b3e8' => 'Estado',
	'1a476e67' => 'Todavía no hay claves de acceso.',
	'd5f8720d' => 'Una clave permite a un programa — el bot de Discord, una integración — leer o escribir en el sitio a través de la API, solo con los permisos que le otorgue.',
	'5ba5fc51' => 'Dirección de la API: %s — cada petición lleva la cabecera %s.',
	'fe916ce8' => 'Claves de acceso',
	'05263085' => 'Nueva clave',
	'e1410c8a' => 'Para reconocer la clave: «Bot de Discord», «Integración del equipo»…',
	'2a5c2d55' => 'Otorgue solo los permisos que el programa necesita.',
	'e2d08a3c' => 'Crear la clave',
	'f789c08b' => 'Clave creada',
	'9dc59300' => 'Copie esta clave ahora: no se volverá a mostrar. Si la pierde, revóquela y cree otra.',
	'84a6d968' => 'Clave de acceso',
	'a080ab79' => 'Volver a las claves',
	'339cadad' => 'Clave revocada.',
	'fe667d1b' => 'Demasiadas peticiones. Inténtelo más tarde.',
	'619618bc' => 'Clave de acceso ausente, no válida o revocada.',
	'd129aab8' => 'Esta clave no tiene el permiso «%s».',
	'fa0787ba' => 'Método no permitido en esta dirección.',
	'569e32bc' => 'Dirección desconocida de la API.',
	'25d8c6f6' => 'Miembro no encontrado.',
	'd507cfac' => 'Ningún miembro ha vinculado esta cuenta de Discord.',
	'240cfde5' => 'El foro no está instalado en este sitio.',
	'8d3f0801' => 'Seguir el flujo de eventos',
	'39fde08d' => 'Tema no encontrado.',
	'740e4d7e' => 'Mensaje no encontrado.',
	'14452488' => 'Escribir en el foro en nombre de un miembro o de una cuenta de Discord',
	'36aed174' => 'Foro desconocido.',
	'04fbbb26' => 'Este foro es un enlace a una dirección externa.',
	'01f6d1f0' => 'De 1 a %d caracteres.',
	'd24c4896' => 'Prefijo desconocido.',
	'b4369901' => 'Este tema está bloqueado.',
	'80938f81' => 'El primer mensaje de un tema no se puede eliminar mediante la API.',
	'd4d5187a' => 'Eliminado desde un programa vinculado al sitio (API).',
	'39824a6f' => 'Solo el autor de este mensaje puede modificarlo o eliminarlo mediante la API.',
	'9e49da1d' => 'Se espera un autor: author.member_id, o author.discord con su id (un número) y su username.',
	'df7fef5b' => '«markdown» o «html».',
	'3eb6574b' => 'El contenido queda vacío una vez limpiado.',
	'd5e9c4a6' => 'El cuerpo de la petición no es un JSON válido.',
	'b2ee4e4b' => 'Algunos campos no son válidos.',
];
