<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'L’API REST du site : des clés d’accès pour les programmes (le bot Discord, une intégration), des adresses versionnées qui rendent du JSON.',
	'8b488245' => 'Gérer les clés d’accès',
	'5bcb4267' => 'Lire les membres et les groupes',
	'94a604be' => 'Lire le forum',
	'4639a8f5' => 'Jamais',
	'4cb2f934' => 'Active',
	'559e8608' => 'Révoquée',
	'e82fd19a' => 'Révoquer cette clé ? Le programme qui l’utilise perdra l’accès immédiatement.',
	'7d9647c7' => 'Révoquer',
	'a6f5854a' => 'Clé',
	'0005d1f8' => 'Droits',
	'a9888d2f' => 'Dernier usage',
	'80b0b3e8' => 'État',
	'1a476e67' => 'Aucune clé d’accès pour le moment.',
	'd5f8720d' => 'Une clé permet à un programme — le bot Discord, une intégration — de lire ou d’écrire sur le site par l’API, avec les seuls droits que vous lui donnez.',
	'5ba5fc51' => 'Adresse de l’API : %s — chaque requête porte l’en-tête %s.',
	'fe916ce8' => 'Clés d’accès',
	'05263085' => 'Nouvelle clé',
	'e1410c8a' => 'Pour reconnaître la clé : « Bot Discord », « Intégration de l’équipe »…',
	'2a5c2d55' => 'Ne donnez que les droits dont le programme a besoin.',
	'e2d08a3c' => 'Créer la clé',
	'f789c08b' => 'Clé créée',
	'9dc59300' => 'Copiez cette clé maintenant : elle ne sera plus jamais affichée. Si vous la perdez, révoquez-la et créez-en une autre.',
	'84a6d968' => 'Clé d’accès',
	'a080ab79' => 'Retour aux clés',
	'339cadad' => 'Clé révoquée.',
	'fe667d1b' => 'Trop de requêtes. Réessayez plus tard.',
	'619618bc' => 'Clé d’accès absente, invalide ou révoquée.',
	'd129aab8' => 'Cette clé n’a pas le droit « %s ».',
	'fa0787ba' => 'Méthode non permise sur cette adresse.',
	'569e32bc' => 'Adresse inconnue de l’API.',
	'25d8c6f6' => 'Membre introuvable.',
	'd507cfac' => 'Aucun membre n’a lié ce compte Discord.',
	'240cfde5' => 'Le forum n’est pas installé sur ce site.',
	'8d3f0801' => 'Suivre le fil d’événements',
	'39fde08d' => 'Sujet introuvable.',
	'740e4d7e' => 'Message introuvable.',
	'14452488' => 'Écrire sur le forum au nom d’un membre ou d’un compte Discord',
	'36aed174' => 'Forum inconnu.',
	'04fbbb26' => 'Ce forum est un lien vers une adresse extérieure.',
	'01f6d1f0' => 'De 1 à %d caractères.',
	'd24c4896' => 'Préfixe inconnu.',
	'b4369901' => 'Ce sujet est verrouillé.',
	'80938f81' => 'Le premier message d’un sujet ne se supprime pas par l’API.',
	'd4d5187a' => 'Supprimé depuis un programme relié au site (API).',
	'39824a6f' => 'Seul l’auteur de ce message peut le modifier ou le supprimer par l’API.',
	'9e49da1d' => 'Un auteur est attendu : author.member_id, ou author.discord avec son id (un nombre) et son username.',
	'df7fef5b' => '« markdown » ou « html ».',
	'3eb6574b' => 'Le contenu est vide une fois nettoyé.',
	'd5e9c4a6' => 'Le corps de la requête n’est pas un JSON valide.',
	'b2ee4e4b' => 'Certains champs sont invalides.',
];
