<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'L\'API REST del sito: chiavi di accesso per i programmi (il bot Discord, un\'integrazione), indirizzi versionati che restituiscono JSON.',
	'8b488245' => 'Gestire le chiavi di accesso',
	'5bcb4267' => 'Leggere i membri e i gruppi',
	'94a604be' => 'Leggere il forum',
	'4639a8f5' => 'Mai',
	'4cb2f934' => 'Attivo',
	'559e8608' => 'Revocata',
	'e82fd19a' => 'Revocare questa chiave? Il programma che la usa perderà subito l\'accesso.',
	'7d9647c7' => 'Revoca',
	'a6f5854a' => 'Chiave',
	'0005d1f8' => 'Permessi',
	'a9888d2f' => 'Ultimo utilizzo',
	'80b0b3e8' => 'Stato',
	'1a476e67' => 'Ancora nessuna chiave di accesso.',
	'd5f8720d' => 'Una chiave permette a un programma — il bot Discord, un\'integrazione — di leggere o scrivere sul sito tramite l\'API, con i soli permessi che gli concedi.',
	'5ba5fc51' => 'Indirizzo dell\'API: %s — ogni richiesta porta l\'intestazione %s.',
	'fe916ce8' => 'Chiavi di accesso',
	'05263085' => 'Nuova chiave',
	'e1410c8a' => 'Per riconoscere la chiave: «Bot Discord», «Integrazione del team»…',
	'2a5c2d55' => 'Concedi solo i permessi di cui il programma ha bisogno.',
	'e2d08a3c' => 'Crea la chiave',
	'f789c08b' => 'Chiave creata',
	'9dc59300' => 'Copia questa chiave ora: non verrà più mostrata. Se la perdi, revocala e creane un\'altra.',
	'84a6d968' => 'Chiave di accesso',
	'a080ab79' => 'Torna alle chiavi',
	'339cadad' => 'Chiave revocata.',
	'fe667d1b' => 'Troppe richieste. Riprova più tardi.',
	'619618bc' => 'Chiave di accesso assente, non valida o revocata.',
	'd129aab8' => 'Questa chiave non ha il permesso «%s».',
	'fa0787ba' => 'Metodo non consentito su questo indirizzo.',
	'569e32bc' => 'Indirizzo sconosciuto dell\'API.',
	'25d8c6f6' => 'Membro non trovato.',
	'd507cfac' => 'Nessun membro ha collegato questo account Discord.',
	'240cfde5' => 'Il forum non è installato su questo sito.',
	'8d3f0801' => 'Seguire il flusso di eventi',
	'39fde08d' => 'Argomento non trovato.',
	'740e4d7e' => 'Messaggio non trovato.',
	'14452488' => 'Scrivere sul forum a nome di un membro o di un account Discord',
	'36aed174' => 'Forum sconosciuto.',
	'04fbbb26' => 'Questo forum è un collegamento a un indirizzo esterno.',
	'01f6d1f0' => 'Da 1 a %d caratteri.',
	'd24c4896' => 'Prefisso sconosciuto.',
	'b4369901' => 'Questo argomento è bloccato.',
	'80938f81' => 'Il primo messaggio di un argomento non si elimina tramite l\'API.',
	'd4d5187a' => 'Eliminato da un programma collegato al sito (API).',
	'39824a6f' => 'Solo l\'autore di questo messaggio può modificarlo o eliminarlo tramite l\'API.',
	'9e49da1d' => 'È atteso un autore: author.member_id, oppure author.discord con il suo id (un numero) e il suo username.',
	'df7fef5b' => '«markdown» o «html».',
	'3eb6574b' => 'Il contenuto è vuoto una volta ripulito.',
	'd5e9c4a6' => 'Il corpo della richiesta non è un JSON valido.',
	'b2ee4e4b' => 'Alcuni campi non sono validi.',
];
