<?php
declare(strict_types=1);
/**
 * https://translate.neofr.ag
 */

return [
	'3ba29a85' => 'API',
	'edbb45b6' => 'A API REST do site: chaves de acesso para programas (o bot do Discord, uma integração), endereços versionados que devolvem JSON.',
	'8b488245' => 'Gerir as chaves de acesso',
	'5bcb4267' => 'Ler os membros e os grupos',
	'94a604be' => 'Ler o fórum',
	'4639a8f5' => 'Nunca',
	'4cb2f934' => 'Ativo',
	'559e8608' => 'Revogada',
	'e82fd19a' => 'Revogar esta chave? O programa que a usa perderá o acesso de imediato.',
	'7d9647c7' => 'Revogar',
	'a6f5854a' => 'Chave',
	'0005d1f8' => 'Permissões',
	'a9888d2f' => 'Última utilização',
	'80b0b3e8' => 'Estado',
	'1a476e67' => 'Ainda não há chaves de acesso.',
	'd5f8720d' => 'Uma chave permite a um programa — o bot do Discord, uma integração — ler ou escrever no site através da API, apenas com as permissões que lhe der.',
	'5ba5fc51' => 'Endereço da API: %s — cada pedido leva o cabeçalho %s.',
	'fe916ce8' => 'Chaves de acesso',
	'05263085' => 'Nova chave',
	'e1410c8a' => 'Para reconhecer a chave: «Bot do Discord», «Integração da equipa»…',
	'2a5c2d55' => 'Dê apenas as permissões de que o programa precisa.',
	'e2d08a3c' => 'Criar a chave',
	'f789c08b' => 'Chave criada',
	'9dc59300' => 'Copie esta chave agora: nunca mais será mostrada. Se a perder, revogue-a e crie outra.',
	'84a6d968' => 'Chave de acesso',
	'a080ab79' => 'Voltar às chaves',
	'339cadad' => 'Chave revogada.',
	'fe667d1b' => 'Demasiados pedidos. Tente mais tarde.',
	'619618bc' => 'Chave de acesso ausente, inválida ou revogada.',
	'd129aab8' => 'Esta chave não tem a permissão «%s».',
	'fa0787ba' => 'Método não permitido neste endereço.',
	'569e32bc' => 'Endereço desconhecido da API.',
	'25d8c6f6' => 'Membro não encontrado.',
	'd507cfac' => 'Nenhum membro associou esta conta do Discord.',
	'240cfde5' => 'O fórum não está instalado neste site.',
	'8d3f0801' => 'Seguir o fluxo de eventos',
	'39fde08d' => 'Tópico não encontrado.',
	'740e4d7e' => 'Mensagem não encontrada.',
	'14452488' => 'Escrever no fórum em nome de um membro ou de uma conta do Discord',
	'36aed174' => 'Fórum desconhecido.',
	'04fbbb26' => 'Este fórum é uma ligação para um endereço externo.',
	'01f6d1f0' => 'De 1 a %d caracteres.',
	'd24c4896' => 'Prefixo desconhecido.',
	'b4369901' => 'Este tópico está bloqueado.',
	'80938f81' => 'A primeira mensagem de um tópico não se elimina através da API.',
	'd4d5187a' => 'Eliminado a partir de um programa ligado ao site (API).',
	'39824a6f' => 'Só o autor desta mensagem a pode alterar ou eliminar através da API.',
	'9e49da1d' => 'Espera-se um autor: author.member_id, ou author.discord com o seu id (um número) e o seu username.',
	'df7fef5b' => '«markdown» ou «html».',
	'3eb6574b' => 'O conteúdo fica vazio depois de limpo.',
	'd5e9c4a6' => 'O corpo do pedido não é um JSON válido.',
	'b2ee4e4b' => 'Alguns campos são inválidos.',
	'7cb47b88' => 'Ser o bot do Discord do site (a sua configuração, incluindo a chave do Discord)',
	'3a8dd48c' => 'O módulo Discord não está instalado neste site.',
	'a1a0582d' => 'Nenhuma ligação para este elemento.',
];
